### ISSUE TITLE
Quote flowing messes up lists with long entries

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#100]
When Cerb replies to a message with long entries, it reflows the quote to fit in an 80 character line, but discards the inherent line separation of lists that exceed 80 characters in length.

We should try to make those look nicer, if we can.
![image](https://cloud.githubusercontent.com/assets/64052/23682419/8fda4aa8-0348-11e7-960b-a02e10da5be5.png)

**Comment by jstanden** [comment]
Fixed in 7.3.5
