### ISSUE TITLE
Allow VAs / Bots to set Worker fields / variables based on the content of others

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#101]
Migrated from JIRA - https://wgmdev.atlassian.net/browse/CHD-4503

Worker fields can be set right now based on a worklist of workers, the workers from a group, and if present, a worker list variable.
This enhancement request is to allow bots to set worker fields based on the content of a different worker field.
For example, if an incoming email is from an address with an assigned Account Manager, then set the Account Manager field on the ticket, or relay that email to the Account Manager, or add that worker as a watcher, or... (Since Relay is the primary target, and it already takes VA variables, we really just need to be able to set the VA Worker-type variable based on a known (linked) Worker field / custom field.)

**Comment by jstanden** [comment]
This is now possible with bot 'Record' actions in 8.2.2.
