### ISSUE TITLE
Allow bots to set record link custom fields from worklist search results

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#102]
The use case in this instance is a server-type record link that's a custom field on the ticket.  The user is able to pull the server info from the incoming email and identify it in a worklist, but then does not have the ability to set the value of the custom field to the object just identified.

> I do like to select the custom_field / record-link (server / domain) also by an bot so the coworker maybe has not to set it manually (only verify) You already wrote a guide how to extract text from emails. This works perfect, i can get the server or domain name from the customers email content. I can set the behaviour variable ( the list of servers / domains). Also can i access the single object, the one domain/server, found in the email… i find by the quicksearch inside the list [thanks your great simulator :D]). But i can't write this record to the custom_field. I know, i could use the link-feature and link the server/domain to the ticket. But like this, i can link several domains/servers to the ticket. It just thought it would be nice to use the custom_field function to store the one and only server/domain, a ticket belongs to

**Comment by jstanden** [comment]
This can be done with bot 'Record' actions in 8.2.2.
