### ISSUE TITLE
Overly long object names overflow their column in Search

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1041]
An overly long object name can obscure the object to its right in the search columns:
![image](https://user-images.githubusercontent.com/64052/68332841-43bb6f00-008c-11ea-9e7e-a7c0e41c064e.png)

Current behavior when hovering is:
![image](https://user-images.githubusercontent.com/64052/68332811-3605e980-008c-11ea-8592-3f94e2b3ff0e.png)

Desired behavior when not hovering is to not obscure the other columns.  Possibly through culling the overflow (like current hover behavior), or by truncating or wrapping the title.

I think ideally, we'd want to show the full object name when hovering, though, so perhaps the current hover view can become the non-hover view, and the new hover view can show the full object name somehow.

**Comment by jstanden** [comment]
This was reimplemented completely in 10.x for the automation-suggested record types for search.
