### ISSUE TITLE
`Esc` doesn't close peek in certain circumstances

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1048]
Browser is latest Chrome, on Windows 10 (if it matters).  Eval was on a ticket peek, might happen elsewhere.  This is *seriously* minor.

Peek -> `Esc`, popup closes
Peek -> prev message -> `Esc`, popup closes.
Peek -> prev message -> next message -> `Esc`, popup fails to close.

It appears to be the case that, after moving around in the list of messages, `Esc` will fail to close the popup if you are on either the first or last message, but it works properly on any intermediate message.

**Comment by jstanden** [comment]
This is probably a focus issue, where the event isn't bubbling up to the popup. I'll give it a test.

**Comment by jstanden** [comment]
Yeah, I can repro in Chrome but not Safari.

**Comment by jstanden** [comment]
k, for 9.3.8 we focus the 'prev' button when you hit the end, and 'next' when you hit the beginning. In Chrome that allows ESC to bubble up, and it also make keyboard nav more user friendly.

**Comment by jstanden** [comment]
Actually, moving this to 9.4, since it affects the new timeline card widget. We could backport the fix to 9.3.8 if it becomes an issue.
