### ISSUE TITLE
[Snippets] Allow inserting snippet without new-line

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1053]
I'm using snippets also to extend some simple words in a reply. I can save my time in adding manually a few examples of what i mean. 

For exemple:
mailclient -> mailclient (MS Outlook, Thunderbird, Mac Mail, ...)
operating-system -> operating system (MS Windows, Apple MacOS, Linux ...)

Those snippets are inserted _inline_, within a phrase.  But inserting them, causes a line- break, which has to be fixed manually every time. I know, this is only a key-stroke. But as Henry Ford said «Save ten steps a day for each of twelve thousand employees and you will have saved fifty miles of wasted motion and misspent energy.» ;-)

There may be other advantages, or even disadvantages i didn't thought about right now. So just let me know.

**Comment by jstanden** [comment]
Fixed in 9.5.4. You can now `#snippet` inline. Newlines are inherited from the snippet, and if there aren't trailing newlines then the cursor is moved to the end of the pasted text on the same line.
