### ISSUE TITLE
[Custom Fields] Field aliases/URIs

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#1079]

**Comment by beatbesmer** [comment]
There are regularly imports of packages, which also contains CustomFields and references to other CustomFields. Those links to existing CFs can be made easily thanks to prompted values while importing a package 👍.
But when you would like to use the API, the developer must know the IDs of each CustomField. He must get those IDs from the current CERB installation. When there are many installations which have imported the same package, those IDs will vary. It would be much easier to document the usage, if there would be a permanent alias instead a variable number.

**Comment by jstanden** [comment]
Implemented in 10.0
