### ISSUE TITLE
[responsibilities] responsibilities are unintenitally reset to default

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#108]
I haven't found a way to reproduce yet, but in 7.2 it seems that responsibilities are reset to default (middle) possibly when adding new buckets or groups. Because each time I had the complaint it was after something changed in groups/buckets. 

I've had this happen 4 times now but each attempt to reproduce seems to fail. So I don't know how it happens but it does.

**Comment by nbeernink** [comment]
@jstanden We just ran into this issue again. This time we had luck and managed to reproduce.  Responsibilities are reset when a member is made manager. (or maybe when any change is made to a group's roster)

This is on 7.2 but may also happen on newer versions.

**Comment by jstanden** [comment]
@nbeernink Thanks! I'll attempt to repro.

**Comment by jstanden** [comment]
@nbeernink I can't repro in 7.3/7.4/8.0, either with an admin or worker account.

When you make them a manager, are you doing it from the worker popup or the group popup?  I tried both.

If you remove them from the group in between then it wipes the responsibilities, but not when going from member->manager or manager->member.

**Comment by nbeernink** [comment]
Very weird. We just retried it and indeed failed... :(

Can redis or elasticsearch be involved? Since we're using those.
Could it be related to #66?

**Comment by jstanden** [comment]
We're using Redis for all of Cerb Cloud.  We used Elasticsearch for a bit, but aren't currently.  I haven't had another report of the same issue.

If you were impersonating at the time, perhaps #66 played some role.

I'm sure what you're seeing is happening in your version.  We just need to track down the actual steps.  I'll dig around a little more this afternoon and try to trace backwards from where the responsibilities are set.

**Comment by jstanden** [comment]
We can revisit this if it happens again. We've never been able to reproduce it.

**Comment by Hildy** [comment]
We've got repro instructions - it's based on editing group membership from the group profile page, which then resets group responsibilities.

**Comment by jstanden** [comment]
Finally fixed in 8.2.7
