### ISSUE TITLE
Ctrl-Shift-Enter behavior is inconsistent

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1094]
Test is on 9.4.0

When you hit Ctrl-Shift-Enter in the body of a reply, it scrolls the screen and focuses the 'Send message' button, and you just have to hit Enter again to send it.  When you do Ctrl-Shift-Enter in the "When would you like to resume..." box, it sends the message immediately like it used to.

**Comment by jstanden** [comment]
This was fixed in 9.4.4. `Ctrl+Enter` focuses the button, `Ctrl+Shift+Enter` clicks it.
