### ISSUE TITLE
Strip blank lines between quoted lines

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#111]
Some MUAs generate really ugly plain text versions of their emails, and you might end up with something like:

> <pre>> This is the first line of the email
> 
> > This is the second line
> 
> > And now the third</pre>

While it's important to only do this in quoted/blank mixed sections, we should strip those empty (non-quoted) lines so that the code to collapse sets of quoted text can actually work on these.

**Comment by jstanden** [comment]
I believed we fixed this in a 7.3.x maint update.
