### ISSUE TITLE
[Sheets/Style] Add a `row:color_template:` option to sheets to conditionally color rows

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#1111]
> Are there any plan to add the possibility to format (for example to
> colorize ;-) the entire row of a table-type sheet according to a specific
> value in the current record ?

Yeah, we've considered it and undoubtedly will do it. It would be much easier/cleaner to do in sheets than in worklists.

Worklists currently require a bot behavior to scan the list and modify the DOM with jQuery (messy!).

With sheets, we just need to tweak the sheet schema syntax to add something like a `row:` object, which could have a property like `color:` and `color_template:`.

`color_template:` would allow you to use bot scripting to conditionally pick a color based on any of the keys/values of that row. We'd likely also provide an internal property for the row counter, so you could do your own alternating row colors, and so on.

**Comment by testdummyaccount** [comment]
Hi. In worklists we used "Record worklist rendered" to highlight the rows differently according some conditions / fields. As an internal update to version 10 is coming soon, we are considering to redesign some legacy worklists using sheets. Now we are wondering: Is there a recommended workaround for sheets until a native function is available?

**Comment by jstanden** [comment]
Implemented in 10.4
