### ISSUE TITLE
Strip quoted nothingness

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#112]
Sometimes we'll see messages that, for whatever reason in the sequence of their quoting, end up with blocks of text like this:

> <pre>> > > > >
> >
> > >
> >
> > > >
> >
> > >
> >
> > > > > > >
> >
> > >
> >
> > > >
> >
> > >
> >
> > > > > >
> >
> > >
> >
> > > >
> >
> > >
> ></pre>

There's really no reason to keep that garbage around, so we should just strip long sequences of quoted blanks (probably any section of 3 or more lines like this).

**Comment by jstanden** [comment]
I believed we fixed this in a 7.3.x maint update.
