### ISSUE TITLE
Multi-checkbox not set during reply

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1124]
To repro:
Multi-checkbox custom field as part of a custom fieldset
Reply to a ticket, add the fieldset, and "set" one or more of the checkboxes.
Send the reply, then edit the ticket

In Edit, you'll see that the fieldset has been added, but the checkboxes are not selected.

**Comment by jstanden** [comment]
I can reproduce this. I believe it has to do with moving the 'set custom field' functionality into a generalized method. That method doesn't consider the set/unset bit on checkboxes.

I'll test every custom field type from reply and get this patched up.

**Comment by jstanden** [comment]
Fixed in 9.4.6
