### ISSUE TITLE
[Compose/Reply] Add a shortcut to insert #snippet

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1136]
A shortcut might save some microseconts to type sequently the keys #sn ... :)

Similiar to CTRL-SHIFT-G for the signature

According https://github.com/jstanden/cerb/commit/bc474dc6ff9b3ed825b0306d6a7d91e83926fc04 "This autocompletes the names of the most frequently used snippets that are usable by the current worker. "
Is this list limited or just sorted by the most frequently used?

**Comment by beatbesmer** [comment]
I also received some user-feedbacks:
Some worker are missing the live- filtering after pressing CTRL-SHIFT-I. So i propose them the usage of the #snippet command... in reply they ask if the additional keystrokes (compared to the previous version) could be saved

**Comment by jstanden** [comment]
Implemented (potentially temporarily) as `Ctrl+Shift+Period` in 9.4.7. This inserts the `#snippet ` text automatically and immediately offers suggestions.

**Comment by jstanden** [comment]
@beatbesmer To your specific question, the suggestions from `#snippet` are sorted by most total uses at the moment. They should be by the worker's own uses, but `worklist.records` doesn't currently support sorting on that virtual column (it's an intermediary table and its usual approach doesn't work). We're currently refactoring this. It was related to the issue where sorting on 'My Uses' was unintentionally disabled entirely.
