### ISSUE TITLE
[Snippets] Can't sort by "My Uses"

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1138]
**Search -> Snippets** nor **CTRL-I** let you sort the snippets by field "MyUses"

You can click to the head of the column "My Uses", which now indicates the sorting direction, but the result isn't sorted as expected

**Comment by jstanden** [comment]
I can reproduce this. Investigating.

**Comment by jstanden** [comment]
Fixed in 9.4.7
