### ISSUE TITLE
Organization field in Compose is ignored

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1155]
Compose a couple new tickets, both with Org, watchers, owner, etc.  Make 'em identical except for sending one to an actual recipient and leave the To line blank on the other.  The one without a To entry loses the Org link.

Further testing exposes that if an Org is set that doesn't match the Org of the To line, the Org of the To line takes over.  Also if no org is set.

In short, a Compose'd ticket will have an org linked to it if and only if the recipient has an org.  Furthermore, I tested with multiple recipients, and it only uses the org from the first recipient, even if the second recipient has a valid org.

There are other options that could be tested (first recipient doesn't have an org, second does, no org set on compose), but this should be sufficient to locate the cause.

**Comment by jstanden** [comment]
Fixed in 10.2.7
