### ISSUE TITLE
[Twig] PHP 7.4 and twig 1.4 - strips whitespace

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1167]
Workaround is to use PHP 7.3, but updating Twig is the long-term solution.  Our patches just need reapplied

**Comment by jstanden** [comment]
This is addressed for 9.5 by upgrading Twig to 3.0.2 (from 1.33.2). We had to make some other changes, but I'm not seeing any issues yet.

**Comment by jstanden** [comment]
Fixed in 9.5
