### ISSUE TITLE
Record changed behaviors for snippets

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1175]
More detail in linked ticket, but the basic gist is a desire to act via bot behavior when a snippet changes.

**Comment by jstanden** [comment]
This should be possible with `record.changed` automation events in 10.0.

**Comment by testdummyaccount** [comment]
I confirm, this is now possible with 
~~~
automation/snippet_has_changed:
  uri: cerb:automation:cerb.snippet.manager
  disabled@bool: {{record__context is not record type ('snippet')}}
~~~
I guess this issue could be considered closed

**Comment by jstanden** [comment]
Perfect! Thanks for confirming. 👍
