### ISSUE TITLE
[Card/Edit] Button of linked custom record (message) not showed properly

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1181]
How to reproduce:

1. Add Custom Fieldset to Tasks
2. Add a Custom Field of type Record Link (message) to this Fieldset (# 1)
3. Edit an existing Task, you'll see the prompt for this Custom Field (# 2)
4. Select an record of type message, and it's subject will be showed as a button (# 3)
5. Save those changes and reopen the dialog, the previously selected value isn't visible anymore, but it seems still there, (# 4). A mouseover let you click to the (x) to remove it.

![image](https://user-images.githubusercontent.com/17173365/73755189-f40d4200-4765-11ea-82ae-8fc59d6eacdd.png)

**Comment by beatbesmer** [comment]
And in the View Mode, those links aren't clickable. Expected was that the corresponding record would open

**Comment by jstanden** [comment]
I believe this was fixed in 9.6.x.
