### ISSUE TITLE
Whitelist attachment types/names in Mail Filtering

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1182]
In Mail Filter behaviors, there's an action for removing attachments based on the filename, but the converse (allowing them based on that) isn't possible.  A customer (linked ticket) wants to only allow certain filename extensions, and mail filtering is just a progressively larger list of not this, not that, not the other thing...

**Comment by jstanden** [comment]
This would be easier with automations, where you could implement the whitelist in code. Behaviors are less flexible and deprecated.
