### ISSUE TITLE
[Records/Bulk] Setting 'record links' custom fields from bulk update doesn't work

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#1204]

**Comment by jstanden** [comment]
@mryanb What record type was the custom field?

I'm not able to reproduce this from tasks.

**Comment by mryanb** [comment]
@jstanden It was a `Record Links` (multiple record links) on a contact record.

**Comment by jstanden** [comment]
Got it! I filed this as 'Record link', but it should be 'Record links'. I'll run it back through testing.

**Comment by jstanden** [comment]
Fixed in 9.4.11

This had to do with the fact the custom field type was from a plugin extension, and there wasn't any special handling for multi-value types. The values were being flattened to 'Array', among other issues.
