### ISSUE TITLE
Bot action titles with double quotes are not escaped/rendered properly in simulator

### ISSUE THREAD

**Issue by mryanb** [jstanden/cerb#1205]
Titles for bot actions are not escaped properly when viewed in the simulator log:
 
Title: `Create "contact" record` gets rendered as
![image](https://user-images.githubusercontent.com/3656391/74178504-543a3300-4c01-11ea-8f2a-75d0adb4543f.png)

**Comment by jstanden** [comment]
Closing. We're phasing out bot behaviors in 10.x. Use automations.
