### ISSUE TITLE
[Mail/UX] usage of #snippet command erases current line

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1226]
**How to reproduce:**
Start to write a phrase, press # and choose snippet.
Almost the same while using `Ctrl+Shift+Period`. Then the command won't be recognized, you'll have to press `backspace` and `enter` to get same error

**Important?**
In most cases this won't disturb your workflow... but if you'r using snippets "inline" within an existing phrase (as in https://github.com/jstanden/cerb/issues/1053), this _could_ be annoying.

As workaround you can use the legacy way (CTRL-SHIFT-I).

**Comment by xtaler** [comment]
upgraded to Cerb 9.5.0
We can't insert snippet for a new message, but we can insert snippet when we reply a message.
Thanks

**Comment by jstanden** [comment]
@xtaler Fixed in `cerb/cerb-release`. Thanks for the report!

**Comment by jstanden** [comment]
Implemented in 9.5.4. You can now use inline snippets. The `#snippet` command no longer replaces the entire current line.
