### ISSUE TITLE
New CSRF checks and API access: CSRF Block: No origin or referrer

### ISSUE THREAD

**Issue by sthen** [jstanden/cerb#1234]
We have some API access that is now blocked in 9.5 with "[Cerb] CSRF Block: No origin or referrer", this was noticed with a PATCH request to /rest/records/address/upsert.json.

It looks like we may be able to just set Origin on requests as a workaround, but was this change intentional? I don't see anything in 9.5.0 release notes suggesting that API calls need changes.

**Comment by sthen** [comment]
If we send Origin it gets further but then fails with the check around the commented-out log entry "[Cerb] Possible CSRF attack from IP %s using referer %s" (devblocks/api/Engine.php:664).

**Comment by jstanden** [comment]
We'll issue a patch to whitelist the `/rest` controller in the new CSRF code so you don't have to add `Origin:` headers manually. I'll ping back here shortly.

**Comment by jstanden** [comment]
The API is exempt from CSRF checks now in `cerb/cerb-release`

**Comment by sthen** [comment]
Great, many thanks for the quick response Jeff!
