### ISSUE TITLE
[Form interaction] Add conditional logic to widget

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1240]
This Feature-Request aims to individualize the form interaction displayed, depending the current record profil opened.

Concrete Ideas for useful variables:
**Current Worker** -> Form interaction could be set depending the "rights" or "groups" of a current worker
**Record** -> if the current ticket is flagged as "migration", additional "migration form interactions" could be displayed in a "global form interaction widget"

This would allow a more fine-grained individualization than only with https://github.com/jstanden/cerb/issues/991, where we're "limited" to entire widgets

**Comment by jstanden** [comment]
This is possible with interactions and toolbars in 10.0 now.
