### ISSUE TITLE
Allow behaviors to set attachment MIME type

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1244]
Once 9.6 is out with the 'record created' event, we should make sure a) that attachments have a trigger point and b) we can update the attachment to set the MIME type.

This will be useful for MUAs that send email with images attached that are encoded as 'application/octet-stream' (instead of 'image/png' or whatever).

**Comment by jstanden** [comment]
You can use a **Records -> Update** action and the records API to update attachment mime types:

~~~
{# See: https://cerb.ai/docs/records/types/attachment/ #}
{% set json = {
  mime_type: 'image/png',
} %}
{{json|json_encode|json_pretty}}
~~~
