### ISSUE TITLE
Block pre-Chromium Edge from logins

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1247]
Since the older versions have some weird bugs, we should only support the new Chromium-based Edge (>79.0)

**Comment by jstanden** [comment]
See: https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history

**Comment by jstanden** [comment]
Perhaps this could be an automation event on worker logins, which functions like `record.merged` in being able to `deny` the current action.

**Comment by jstanden** [comment]
This can be done now with a `worker.authenticated` automation. It gets browser name + version info, and can reject the login.
