### ISSUE TITLE
[Bot/Custom behavior on ticket] Action "send e-mail to recipients" not working

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1248]
A "custom behavior on ticket record" creates a commend and _should_ also send a message trough `send e-mail to recipients`. The comment is created, but no message is sent.

The attached example behavior is called from an Form- Interaction **variable** of type **ticket**
[send_message_package.json.txt](https://github.com/jstanden/cerb/files/4393922/send_message_package.json.txt)

**Comment by jstanden** [comment]
Closing. We're phasing out bot behaviors in 10.x. Use automations.
