### ISSUE TITLE
[GitHub] Repository migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [jstanden/cerb#1255]
It is possible to migrate the "cerb" personal account to organization?
- https://github.com/cerb
- https://help.github.com/articles/converting-a-user-into-an-organization/

Or:
You can change the username of the account, example "cerb-account", create a new organization "cerb", and move all from old account to the new organization and look for other repositories.

Nothing is lost.

**Comment by jstanden** [comment]
We'll consider this.

**Comment by Neustradamus** [comment]
@jstanden: Several months after, have you plan to migrate the cerb user account to organization?

**Comment by Neustradamus** [comment]
@jstanden: What is the current status?
What are the news about it?
