### ISSUE TITLE
Move to future cerb organization (a message for @rmiddle)

### ISSUE THREAD

**Issue by Neustradamus** [jstanden/cerb#1256]
@rmiddle: It is about https://github.com/rmiddle/cerb5

Can you move to future cerb organization?
- https://help.github.com/articles/about-repository-transfers/

Linked to:
- https://github.com/jstanden/cerb/issues/1255

**Comment by Neustradamus** [comment]
@jstanden: Have you a solution for me, I would like to contact @rmiddle?

**Comment by jstanden** [comment]
As far as I know, he's not a Cerb user anymore. I already have an issue from you on this in the main repository, and don't need extra ones for the forks. Thanks!

**Comment by Neustradamus** [comment]
This request is to move this old cerb for have all in the "main space", it is not the mainline like your repository.

Have you looked for you?

**Comment by jstanden** [comment]
This is being tracked on #1255

**Comment by Neustradamus** [comment]
@rmiddle: It will be logic to transfer into github.com/cerb the repository that you have published a long time ago.
It will be nice.

**Comment by rmiddle** [comment]
@jstanden Yea I am not as active as I once was with Cerberus.  If you need me to move one of my repo around I can.

**Comment by jstanden** [comment]
@rmiddle No worries. I'm not sure why random people are @mentioning you to do things after all this time. I hope you're well. :)

**Comment by Neustradamus** [comment]
@jstanden: It is about https://github.com/rmiddle/cerb5
This repository, to be move into cerb for have historical place...

**Comment by rmiddle** [comment]
> @rmiddle No worries. I'm not sure why random people are @mentioning you to do things after all this time. I hope you're well. :)

I am doing pretty well.  I will see about migrating the repo as that had allot of custom code that isn't relevant now but would be to anyone who was using some of my patches in an older version.

**Comment by rmiddle** [comment]
@jstanden What is the Cerb Organization name to transfer the repo to?

**Comment by jstanden** [comment]
@rmiddle Glad to hear you're well. There isn't an org. This is nothing I'm asking for or working on.

**Comment by Neustradamus** [comment]
@rmiddle: It will be here: @cerb currently an user account.
You can launch a transfer before the convertion without any problems: https://help.github.com/articles/about-repository-transfers/

In your cerb5 repo, in settings and at the bottom -> Transfer ownership
You can select "cerb" and confirm with the old address and your password.

**Comment by jstanden** [comment]
Honestly, that's Cerb5 code (10 years old). It would be entirely unsupported, and we have no incentive to encourage anyone to use it. If you transfer it I'd just archive or delete it.

**Comment by Neustradamus** [comment]
@jstanden: After the transfer, better to archive :)
If the repo is removed, another one will be the upstream of cerb5 and there will have always 6 forks.

**Comment by Neustradamus** [comment]
Dear @webgroupmedia, @wgm team, @jstanden, @Hildy,

Any progress on it?

Thanks in advance.
