### ISSUE TITLE
[Form Interactions] Images instead buttons

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1258]
An use-case with many Form interactions: There are a lot of grey buttons on a site.
Users complained, its hard with all those buttons, when you first have to read all the names till you know where to click. Sure, someday, they'll remember the buttons.. But isn't it possible to show those buttons as a image? To visualize the purpose of their function.

I guess we could manipulate those buttons with some scripts. But, if you'll find time for this idea, this might help others to save some time on scripting:
- allow to add an image to a (form interaction) behavior (similar editor as for bot- Images)
- let this image be displayed instead of a button or above the description (or something similar)
OR maybe
- let integrate some CSS / formatting directly into the form interaction widget

**Comment by jstanden** [comment]
This is possible in 9.6 now using 'Prompt with sheet' in form interactions. The sheet column can include an image, with row selection.
