### ISSUE TITLE
[API/Compose] Fix trailing comma in `POST /tickets/compose` in PHP 7.2

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#1260]
https://github.com/jstanden/cerb/blob/9.5.2/features/cerberusweb.restapi/api/rest/tickets.php#L629

**Comment by beatbesmer** [comment]
Only detected in 9.5.3 an the current cerb-release

https://github.com/jstanden/cerb/blob/9.5.3/features/cerberusweb.restapi/api/rest/tickets.php#L629
https://github.com/cerb/cerb-release/tree/master/features/cerberusweb.restapi/api/rest/tickets.php#L629

**Comment by jstanden** [comment]
Fixed in 9.5.3
