### ISSUE TITLE
Composing a new ticket with no participants doesn't save the specified Org

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1267]
Cerb Cloud customer has a workflow that involves sometimes creating tickets with an Org but no participants.  He reports that recently this stopped saving the Org on the created ticket.

This is perhaps the 9.5.3 update, since that involved some changes to compose and was recently released.  I have confirmed that Compose with an org specified saves the org to the ticket when a participant is specified, and does not save the org to the ticket when there are no participants.

**Comment by Hildy** [comment]
Correction; they're on 9.5.2 still, as is my test site.  I just confirmed that it still doesn't save the Org on 9.5.3, though.

**Comment by jstanden** [comment]
This is because compose went draft-based in 9.5.0+. At that point, the org is only being used to suggest participants.

I can tweak this when there are no participants.

**Comment by jstanden** [comment]
Implemented in 9.5.10
