### ISSUE TITLE
Boolean expression rendering in search filters

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1268]
Some boolean expressions aren't being rendered right in search filter display:

![image](https://user-images.githubusercontent.com/64052/79491555-7a9a9700-7fd3-11ea-8026-361f2937e04c.png)

If you do `status:open OR (owner.id:me status:w)` then it includes the 'AND', but the close paren is still missing.

**Comment by jstanden** [comment]
Fixed in 9.6
