### ISSUE TITLE
[Project Board Column] Can't add a behavior for "When cards are dropped into this column"

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1271]
When you edit a **Project Board Culumn**, in `When cards are dropped into this column:` when you click to `(+) Behaviors` you get an error.

> Notice: Call to undefined internal action `ChInternalController::chooserOpen` in /..../features/cerberusweb.core/api/uri/internal.php on line 42

**Comment by jstanden** [comment]
Thanks! It sounds like this broke in the security audit, since that was backported from the 10.0 branch, and project boards use automations there. We'll get this patched in 9.5/9.6.

**Comment by jstanden** [comment]
Fixed in 9.5.10
