### ISSUE TITLE
[Outcome/Is linked] not available to Custom Records

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1272]
The Behavior **Record Custom Behavior on Task** let you check the linked records for a specific Task.
It seems like this condition is not available for **Custom Records**, 

This is useful in combination with **Project Board Columns**, so you can also check the current status / column of a custom record

**Comment by jstanden** [comment]
Closing. We're phasing out bot behaviors in 10.x. Use automations.
