### ISSUE TITLE
[Project Board Column] Custom Fields not visible / editable

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1273]
You can add **CustomFields** to **Project Board Columns**, but it seems as you can't see / modify them while editing the column.

The initial idea was to add add a **larger "description"** to the column, using a customField (Large title doesn't looks really nice).

(You could also use CustomFields to "group" columns of same type, which are used in different projects, or to add several workers with different roles to a column, if the _Watcher_ isn't enough)

**Comment by jstanden** [comment]
This must have changed recently. You can edit custom fields and fieldsets on project board columns in at least 9.6+ (perhaps slightly earlier).
