### ISSUE TITLE
[Bot/Behavior] Alias / URI not available through API

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1279]
It seems as i can only access an API behavior trough its ID, not by the "Behavior aliases (URIs)" defined. It would be more comfortable to have the alias URI available for API requests. This prevents developer to modify the ID when there was an recreation of a existing bot- behavior or another "internal change"

`$out = $cerb->post($base_url . 'bots/behavior/123/run.json', $postfields);` is working.
`$out = $cerb->post($base_url . 'bots/behavior/myAlias/run.json', $postfields);` gets a "_Not implemented_"

**Comment by jstanden** [comment]
Sure, this should be easy to implement.

**Comment by jstanden** [comment]
Implemented in 9.5.10
