### ISSUE TITLE
Variable seat idle time

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1287]
The concept has been referred to as seat pools, or worker classes; it's a preference-based idle timeout for worker seats.

The idea is to have a worker property, searchable and bulk-updateable, that indicates what a worker's idle time timeout is (for the purposes of forced logouts due to seat limits). '0' could potentially indicate a seat that is never to be kicked off.

Workers who need to remain logged in could have a longer timeout, and then the seat-kick code would evaluate 'idleness' based on those per-worker timeouts instead of based on a flat standard.

**Comment by jstanden** [comment]
Implemented in 9.6
