### ISSUE TITLE
Validation on invalid "reopen" dates

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1297]
Every so often, I'll typo the reopen date just before sending with ctrl-shift-enter.  Since it can't evaluate the date, it ends up blank (with no reopen date).  In this case it was "next mno", but can we have some kind of alert when the contents of that field fail to evaluate to a proper date?

**Comment by jstanden** [comment]
The 9.6-dev changes improve validation on compose/reply, including when sending or saving a draft. The reopen date can be validated as a proper date within that now.
