### ISSUE TITLE
[Ticket/Reply] special characteres in "display name" of sender clears "To:" field

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1302]
One customer uses a display name like
`[ - My Entreprise - ] --- My Name<my.name@my.enterprise.tld>`

Even if it looks ... interessting: while replying, CERB removes it's e-mail address and we've to enter my.name@my.enterprise.tld manually

**Comment by jstanden** [comment]
I tested this in 9.5.5 and it parsed the email address properly:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/63288/82473576-a26f9580-9a7e-11ea-93e1-1dfaeb77585a.png">

Can you look at the raw headers on that message so I can see how the `From:` was encoded?

**Comment by beatbesmer** [comment]
Mea culpa! The environment where this issue occurred was on 9.4.13. Meanwhile, i have tested an mail-import with success on latest release.

**Comment by jstanden** [comment]
Glad to hear it. :)
