### ISSUE TITLE
SC Portal Forgot Password demands old password

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1312]
When you go through the 'forgot password' thing on the portal, it asks you to input your old password so you can set a new one.  It *does* let you log in, but you can't change your password.

**Comment by jstanden** [comment]
There was a security improvement in the SC that requires the current password to change the password. It's worth keeping that.

I agree that when resetting a forgotten password, we shouldn't just piggyback on the old form. We should have the visitor provide a new password before logging in like Cerb does for workers.

**Comment by jstanden** [comment]
Fixed in 9.5.7
