### ISSUE TITLE
[feature request] different list style options in HTML replies

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1313]
The 'list' button in HTML replies could become a menu/dropdown where you can select what kind of list style you'd like to apply to the selected text

**Comment by jstanden** [comment]
This would be easy to do in 10.0 now, since the formatting menu is a KATA toolbar.

**Comment by jstanden** [comment]
Anyone can implement this with toolbars in 10.0 now. See an example in: https://github.com/cerb/cerb-release/discussions/5
