### ISSUE TITLE
[Dashboards/Chart] allow queries as subtotal for chart "worklist.subtotals"

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1314]
Category: nice 2 have

On a chart of type category (worklist.subtotal) we can group several groups by a another subtotal based on a _field_ like **group**
![image](https://user-images.githubusercontent.com/17173365/83876806-b0d5d680-a739-11ea-931a-5cefba60064c.png)

I would be nice, also to have a **query** available as subtotal.
![image](https://user-images.githubusercontent.com/17173365/83877837-7b31ed00-a73b-11ea-9f26-0317e1740d63.png)

We already can do something similar available with **Pie Charts** and type:worklist.metrics and series of values. But this only is limited to one group. We'd have to add several pies, for each group one
![image](https://user-images.githubusercontent.com/17173365/83878380-61dd7080-a73c-11ea-9ae7-79a70c0cf1df.png)

(queries / criterias used in second and third image aren't the best and doesn't match, but should help to understand)

**Comment by jstanden** [comment]
This can be done with [Chart KATA](https://cerb.ai/docs/dashboards/widgets/chart-kata/) now.
