### ISSUE TITLE
Nested square brackets in outgoing HTML email cause problems in plain-text copy

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1328]
Using nested square brackets in an outgoing HTML email causes that line to be missing from the plaintext copy.

Source is:
![image](https://user-images.githubusercontent.com/64052/85788964-a24c6080-b6e2-11ea-9fb3-fcc40203694f.png)

received HTML is:
![image](https://user-images.githubusercontent.com/64052/85789063-cdcf4b00-b6e2-11ea-9218-8f85cc3cc822.png)

Received raw plain-text is:
![image](https://user-images.githubusercontent.com/64052/85788646-281bdc00-b6e2-11ea-8343-a9aa9ea8457c.png)

**Comment by jstanden** [comment]
We need to just use the original Markdown as the plaintext part -- perhaps with just stripping HTML tags.

The issue here comes from the voodoo we do to turn Markdown->HTML->Plaintext.

**Comment by jstanden** [comment]
This is fixed with a stopgap in 9.5.9 by rearranging the operations in the mail service.

It's fixed properly in 9.6 by preserving the original Markdown as the `text/plain` part. We no longer (insanely) up-convert Markdown to HTML then down-convert it for the text part.
