### ISSUE TITLE
Replies and Drafts don't show record links in custom fieldsets

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1330]
The issue here is somewhat two-fold, though there's a single solution.

Test version: 9.5.7, Cerb Cloud (reported Self-Hosted initially)
The preconditions: a ticket, a custom fieldset with a record-link type field (let's call it RLField).

First Issue:
When you reply to a ticket with RLField set, it's not shown as set in the fields below the reply.  If you click that checkbox, it does show the correctly linked record.

Second Issue:
When you save a draft and then resume it, it resumes with the RLField checkbox unchecked, *regardless* of whether there has been a change to that field or the state of the checkbox when the draft was saved.  Checking the box does show the correct link (changed or not).

While the visibility issue is a slight annoyance, the big problem is that if the RLField checkbox is not checked, then that change will not be applied to the ticket when the message is sent.

![image](https://user-images.githubusercontent.com/64052/86490718-36d74400-bd1d-11ea-8ecb-b3a5cab39d3c.png)

**Comment by jstanden** [comment]
This should be resolved in 10.1.
