### ISSUE TITLE
Notifications on comments on comments don't have the right target

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1345]
When you @Notify a worker in a comment on a comment (new to 9.6), the target of the notification isn't properly set in the notice:

![image](https://user-images.githubusercontent.com/64052/89081467-2deb8980-d340-11ea-872b-27fc7721caad.png)

![image](https://user-images.githubusercontent.com/64052/89081489-38a61e80-d340-11ea-9d0b-776b49b242cd.png)

**Comment by jstanden** [comment]
Fixed in 9.6-beta2
