### ISSUE TITLE
The HTML Template custom sig broke in 9.6

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1347]
In 9.5.x, when Composing an email in HTML mode, and with an HTML template selected (see linked ticket for repro example), the custom sig portion of the HTML template was used to replace #signature. 

As of 9.6-beta2, where that sig should be is blank (it doesn't use the default sig's HTML part, either).

Please note that this only applied to Compose, because of another bug (to be filed in a moment).

**Comment by jstanden** [comment]
Fixed in 9.6-beta3
