### ISSUE TITLE
[Mail/Parser] make original header of bounced-messages available if message can't be assigned to an existing ticket

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1366]
There are situations, where an external tool creates messages, but Cerb treats the replies / bounces. Trough a personalized message-id in the original message, we may detect the type of message a bounce / reply is referring to. Unfortunately, sometimes we'd have to read the attached original- message, what isn't implemented yet (see #766 )

I've seen, in the api/app/Parser.php you'r already taking care about bounce- messages (delivery-status, message/rfc822(?)). So, before reinventing the wheel:

Would it be possible to make those "original" informations from those bounce (delivery - status) messages available to a the cerb- owned behavior? I suppose this would need a new type of behavior or filter- condition / function in the "incomming mail filter" behavior

**Comment by jstanden** [comment]
It's possible to `file.read:` from automations now.
