### ISSUE TITLE
Implement more filters in Elasticsearch

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1385]
Now that we've got timeouts on queries in 9.6+, we should be able to rewrite some of the search engine functionality to take other filters into consideration before / while running the fulltext searches.  See linked ticket for more details.

**Comment by jstanden** [comment]
Cerb 10.1+ is going to heavily favor MySQL Fulltext (incorporating all other filters). There's not much benefit to using ES from this point.
