### ISSUE TITLE
Adding / Updating / Deleting a node on a Behavior should modify the Behavior's updated date

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1395]
If you change the nodes on a behavior (adding decision trees, actions, etc), but don't actually edit the base properties of the behavior, it doesn't show as updated.  This makes it harder to find when you're looking for "the behavior I just updated this morning", but it shows as updated 4 years ago. :)

**Comment by jstanden** [comment]
Closing. We're phasing out bot behaviors in 10.x. Use automations.
