### ISSUE TITLE
New object bubbles in the wrong spot

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1401]
Scenario:

Address card popup
Click + to add a contact
On Contact popup, click + to add an Org.
Save Org
Save Contact

Address card now shows both object bubbles as Contacts

![image](https://user-images.githubusercontent.com/64052/97058187-f278e980-1541-11eb-8010-c57e212999e2.png)

**Comment by jstanden** [comment]
Fixed in 9.6.6
