### ISSUE TITLE
Group-owned bots do not have upsert permissions

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1407]
> There's a permissions check in the 'Upsert Record' action based on the owner of the bot. 
> 
> App-owned and role-owned bots are permitted, and group-owned bots are blocked.
> 
> That's an oversight/bug rather than a design decision.
> 
> The app owner is allowed to do anything (like an admin). Role owners have a policy. There's nothing on groups to confer those permissions. Otherwise any group mananger could modify a behavior and circumvent permissions.
> 
> Automations avoid this issue by having an admin-granted policy per automation independent of any owner. We've needed something like that in bots for a while.
> 
> At the very least we can show an obvious error in the meantime.

**Comment by jstanden** [comment]
Closing. We're phasing out bot behaviors in 10.x. Use automations.
