### ISSUE TITLE
Add date interpolation for quarterly results on charts

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1410]
More details are available on the linked ticket, but the main comments:

> The main thing I need to finish is our date lerp (interpolation) for data query results, since "+1 quarter" isn't a permitted time unit. We'd need to do something like "+3 months" from the first of each month. That's used for chart labels.
> 
> I'll also probably break it up to `@quarter` (2020-Q4) and `@quarterofyear` (4). The latter could group quarters between years.

**Comment by jstanden** [comment]
Implemented in 10.3
