### ISSUE TITLE
Adding inbound To/CC recipients is not working

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1412]
9.6.6, and maybe a bit earlier.  Sample email that only adds the 'customer' address:

> To: support@cerb.example, boss@cerb.example
> Cc: cc@cerb.example
> From: customer@cerb.example
> Subject: Testing adding inbound To/Cc recipients
> 
> Testing adding inbound To/Cc recipients

**Comment by jstanden** [comment]
Fixed in 9.6.8
