### ISSUE TITLE
Disable (or warn on) #commands in the middle of a line

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1413]
The reply editors will autocomplete #commands (like #comment) in the middle of a line, but those won't actually be interpreted (they'll be sent to the customer).  

We should either disable autocomplete in the middle of a line like that, or provide some kind of (maybe tooltip?) warning that the command will be sent as-is rather than interpreted.

**Comment by jstanden** [comment]
This could be done with a reply interactive validator (like profanity + missing attachment + non-HTML w/ markup).
