### ISSUE TITLE
Add a ticket field to track customer wait time

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1414]
Some customers would like to be able to sort tickets not by creation or updated date, but by how long the customer has been waiting for a reply.  As an example:

Mary writes in at 8:00
Bob writes in at 8:15
Mary writes in at 8:30 (same ticket as earlier).

In this scenario, when sorted by 'updated' date, it will look like Bob's request is before Mary's, when it really wasn't.

A customer-waiting-since date field (though we'd need a better name) would allow those to be sorted based on the first incoming message after the latest outgoing message.

**Comment by jstanden** [comment]
This was done in 10.2 with the 'last opened at' field and 'time spent open' metric.
