### ISSUE TITLE
Send email action applies internal protection measures in HTML email

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1417]
When using the "Send email" action in a bot behavior, combined with sending HTML email, the links and images are run through the internal protection code, making them useless.  In an image tag, `src="https://example.com/image.gif"` becomes `src="/security/proxyImage?url=https%3A%2F%2Fexample.com%2Fimage.gif"`.  For links, they get the javascript `externalLink` wrapper.  More details and specific examples available on the linked ticket.

**Comment by jstanden** [comment]
I haven't seen this. I assume it's because the UI and scheduler were using different URLs/hosts.
