### ISSUE TITLE
[Kata] Allow additional description to picklist value

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1418]
What if we could add a name to a "picklist" value, similar the HTML- dropdown where the NAME and ID don't have to match?
The user could see a descriptive name, but a short ID is passed to the snippet / TWIG for internal processing.

Concrete:
- there is a list of servers (with FQDN / IP), but in the snippet itself, we could only use the IP.
- also other kind of lists could use a script-internal ID / Key, even the user sees an long(er) description as dropdown value

**Comment by jstanden** [comment]
With [interactions](https://cerb.ai/docs/interactions/) this can be done already with two-line sheets. The `selection:` column in sheets can return any value for the row (ID, name, URI, etc). It can display a separate label and optional description.
