### ISSUE TITLE
Simulator log entries double-escaped

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1434]
The outcome `Don't trigger for...` is displayed in the simulator log as `Don&#039;t trigger for...`

![image](https://user-images.githubusercontent.com/64052/109825758-f94df200-7bee-11eb-9df6-37d213396edb.png)

**Comment by jstanden** [comment]
I'm going to ignore this, since behaviors are deprecated in 10.x and will be removed in 11.x.
