### ISSUE TITLE
[Worklist/Behavior] let the "Outcome" of "Record worklist rendered" access more details from worklist/tab/page

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1435]
There are many visually individualized worklists, where the behavior "Record worklist rendered" executes jQuery scripts. Those scripts are applied globally or depending to the worklist ID.

We'd like to apply some predefined scripts to worklists easily without touching the logic/code. This "selection" of worklists could be implemented by adding a CustomFields or Tags in the Worklists Title, CustomFields or other characteristics in the "Profile Tab" or the "Workspace Page" (owner).

Unfortunately, the behaviors outcome only can access the worklists ID and Type.
Sure we'd create a workaround and read manually the "Worspace Worklist"- Record and also its "Workspace Tab" and "Workspac Page" (or some Persistent- Key). I don't know if those are loaded already and if this additional query will haven an minimal impact to the performance. 

I guess making some more data of a worklist, the belonging Workspace Tab and Workspace Page available in the "Record worklist rendered" behavior, would facilitate the customizing of some selected worklists.

**Comment by jstanden** [comment]
Right now 'Record worklist rendered' only runs against the generated HTML. There are some extra `data-` attributes in recent versions to simplify some workflows (e.g. Unix timestamps on date columns, status bits).

Sheets are better about this.
