### ISSUE TITLE
Inserting the #original_message in an HTML reply doesn't de-duplicate images

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1441]
Images in the original message are inserted with different names, so in a case where people top-post in a thread with signature images, we get a lot of duplicate resources, when those could be consolidated and just linked like we do with our standard image/attachment code.

Ideally, we'd want this to do the standard deduplication, so that even in a read-all scenario on a long thread, we're loading a handful of images instead of hundreds of them.

**Comment by jstanden** [comment]
Fixed in 10.0. We now de-dupe storage objects with the same file type, size, and hash. Previously it required hash and name to match. In these cases, the filenames keep changing.
