### ISSUE TITLE
Be more MySQL specific about FULLTEXT searching and JOINs

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1445]
Basic gist is that, in being generic so that Elasticsearch works similarly to MySQL, we sacrifice some of the preferential JOINs we could use to make FULLTEXT searching faster.  This issue is targeted to making MySQL more a default, and having specific optimization benefits for that.

> As soon as I get some time, I'll probably stop treating MySQL and ES as interchangeable search engine extensions/plugins. We'll leave ES as an extension with the limitations on max results, and we'll make the default fallback MySQL which is part of the core code, can JOIN, and won't have the limits.

**Comment by jstanden** [comment]
Implemented in 10.1. This removes the result limits on MySQL searches and incorporates all other filters.
