### ISSUE TITLE
[Record/Comments] Option to resend @mentions when editing comment

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1447]
Occasionally, people **forget to mention** an co-worker in a comment. It seems that the comment has to be **deleted and recreated** so that the notifications are sent to all mentioned employees.
Many employees are not aware that when they edit a comment afterwards, the new @mentions are not taken into account.

It might be helpful to have an option that allows to trigger the @mentions afterwards.

![image](https://user-images.githubusercontent.com/17173365/115207311-c3f85780-a0fb-11eb-8b3a-73e4dee2a2b8.png)

**Comment by jstanden** [comment]
Dupe
