### ISSUE TITLE
10.0 migration doesn't look at parent bot status for disabling behaviors

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1450]
Jeff's comment:

> The code does actually disable behaviors in automation events if they were disabled before:
> https://github.com/cerb/cerb-release/blob/v10.0/features/cerberusweb.core/patches/10.x/10.0.0.php#L394
> 
> *But* it's only checking if the behavior was disabled, not the parent bot.
> 
> The migration should either explicitly disable all behaviors on disabled bots first, or take the parent bot into account during the process.

**Comment by jstanden** [comment]
Fixed in 10.0
