### ISSUE TITLE
Example of setting up another permissions set (instead of webserver user)

### ISSUE THREAD

**Issue by fliespl** [jstanden/cerb#1452]
In our use case due to security reasons we clone repository files as other user than nginx webserver or php is running from and set them up as only readable by php process.

This is a security precaution in case of error in code which would allow attacker to "inject" script to php files. This way php-fpm / nginx  request won't be able to edit them. We also block php scripts from upload locations (storage/).

What we are missing though is a list of required writable directiories - is it only storage one or is there anything else we are missing? Also - does it require any php scripts to be executable from there?

Currently I can only see version.php in storage.

**Comment by jstanden** [comment]
Hi @fliespl,

Cerb only ever writes within the `storage/` directory. During installation, it _can_ write the `framework.config.php` file for you, but it's not required to be writeable (especially post-installation). With your database and the `storage/` directory you'll have all of the environment-specific data.

The only two directly executable PHP scripts in normal use are `ajax.php` and `index.php` in the top-level directory. Cerb follows the MVC pattern and will route all requests from there.

(You should also [make sure](https://cerb.ai/docs/security/) the `storage/` directory is never accessible to web requests.)

**Comment by fliespl** [comment]
@jstanden thank you very much for confirmation! Appreciate it.

**Comment by jstanden** [comment]
Sure thing! :)
