### ISSUE TITLE
Add an 'after:' option in card toolbars

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1468]
> You can use the `headless@bool: yes` option to close the interaction without any awaits. It won't even open the popup at that point -- just run the action and the `after:`.
> 
> In that 'Participants' example on ticket profiles, that's what the 'Remove participant' option does. It doesn't need to prompt for anything; opposed to the 'Add participant' option that has a sheet chooser.
> 
> We can add an `after:` option in card toolbars to be able to close their popup. That would be the cleanest way.

**Comment by jstanden** [comment]
Implemented in 10.0.4
