### ISSUE TITLE
[bot/custom fields] add validation, requirement and default settings to  custom fields and bot parameters

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#149]
Often times you're making a workflow that requires a specific input. It would help a lot to make it configurable for certain custom fields and parameters. 

I know some of these can be done with current decisions and custom scripts, but those only give feedback after the fact. This is meant to trigger before the data submission. 

* require that the field has (valid) input before uploading
* set up default that is always prefilled
* input validation (could be based on the current type selection + maybe a custom regex) 

The configuration for each parameter could maybe be accessed by clicking an icon next to the drag & drop button, this would prevent adding complexity to the parameter configuration. As I can also imagine it's not always used, and you don't want to always have it in sight. (bloating the interface)

**Comment by jstanden** [comment]
Now that we use "conversational interactions" in 8.0, this happens naturally.  The older macros are no longer called directly by workers.
