### ISSUE TITLE
[Bots/Records] Ability to set all record details using bot-actions

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#150]
Currently it's not possible to set record details for orgs such as country, address, phone, etc. This is currently only possible for custom fields on orgs.

I want to be able to use a bot to pull details from an external source and set them for the selected org.

This could be used in chat convo's too;

> Update [org's] address to: <new address here>
> org's phone number is: <phone number>

Or maybe I've reached the point where I should start using cerb's API to do this stuff...

**Comment by jstanden** [comment]
This is now possible with bot record actions in 8.2.2. You can update any field on any record from a bot behavior of any type.

We'll post a guide shortly.
