### ISSUE TITLE
Subtotals count multi-checkbox custom fields incorrectly

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#151]
When subtotalling a multi-value checkbox custom field, it seems to only show the first value selected.  So with tickets(#) with checkboxes(ABC) like so:

#1 A
#2 A, B, C
#3 A, C

You might end up with the following subtotals
A (1)
B (1)
C (1)
when it should really be
A (3)
B (1)
C (2)

The original report was a customer noticing this on widgets, but it's likely to apply across the board.

**Comment by jstanden** [comment]
Yeah, in my test I had:
A (3)

And nothing else.

**Comment by jstanden** [comment]
Fixed in 7.3.10
