### ISSUE TITLE
SSO with custom oauth2 service

### ISSUE THREAD

**Issue by fliespl** [jstanden/cerb#1521]
Hi @jstanden,
probably answer to my question is so obvious and somewhere in documentation and I will feel totally ashamed, but giving it a go either way! (I have spent quite a lot of time searching though before asking here).

I am trying to incorporate our company solution to create new user accounts based on our oauth2 service.

What I miss is - how to enable & configure it.

Obviously it's possible since I see "You don't have any SSO-enabled connected services configured.".

Yet I fail to find any instructions to add them (shame on me once again!).

Also - does it support switch like "skip MFA"?

**Comment by jstanden** [comment]
Hi @fliespl!

Is this for workers in Cerb or customers in the Support Center?

For workers, Cerb supports SAML or OpenID Connect (OIDC) identity providers.

OpenID examples:
* [Microsoft Azure AD](https://cerb.ai/guides/integrations/azure/sso-openid/)
* [Okta](https://cerb.ai/guides/integrations/okta/sso-openid/)
* [Salesforce](https://cerb.ai/guides/integrations/salesforce/sso-openid/)

SAML example:
* [Google Workspace/G Suite](https://cerb.ai/guides/integrations/google/sso-saml/)

You can use any SAML or OIDC identity provider using connected services.

Navigate to **Search->Connected Services->(+)->Build**. The **Type** would be **OpenID Connect Identity Provider** or **SAML Identity Provider**.

If your provider supports auto-discovery, you can paste that `.well-known` URL into the **Issuer** and click **Run Discovery**. It will fill in the other URLs for you.

With OpenID Connect you'd create an app first at the provider, which generates your client ID and secret. The scope is usually something like `openid profile` or `openid email`.

Once the connected service is configured, you can navigate to **Setup->Security->Authentication** and enable SSO with that provider. On the login form you'll then see a new one-click login button.

On MFA, Cerb's MFA is disabled when you use SSO. You'd have to configure that at the identity provider. When using our auth, MFA can be required for everyone or optionally configured per-worker.

It's worth noting that, at the moment, Cerb doesn't provision new worker accounts from SSO. A worker account will need to exist that matches the `email` claim. In the meantime, you can auto-create workers from any data source using a one-time [package](https://cerb.ai/docs/packages/). See [here](https://github.com/cerb/cerb-release/blob/v10.1/install/packages/install_demo_package.json#L95) for an example. 

We're working on adding a new [automation](https://cerb.ai/docs/automations/) event for provisioning new accounts from SSO. That would allow you to map any data you want to the new worker (roles, group memberships, etc).

**Comment by fliespl** [comment]
Thank you very much @jstanden.

It's about workers. Our initial idea was to hook it up with our internal oauth2 service (not supporting openid just yet) to streamline account creation / login process.

But since you mention account provision is not available at this point this is not a way for us :)

What we planned to achieve:
- allow signup using SSO oauth2 service (with fields mapping) instead of regular login form
- create account if it doesn't exist (based for example on email)
- authorize account if email exist.

Of course minus permissions - which would be assigned by admin acct after acct creation.

At this point we will stick to our normal account setup, but really appreciate your reply! :)

**Comment by jstanden** [comment]
Sure thing! [Packages](https://cerb.ai/docs/packages/) and the [API](https://cerb.ai/docs/api/endpoints/packages/) are still a great way to automate worker account creation.

You can use any of these [worker record fields](https://cerb.ai/docs/records/types/worker/#records-api) in the packages. Then just POST that to the API.

**Comment by fliespl** [comment]
And that's how we will proceed! Thanks much again :)
