### ISSUE TITLE
The first_response_time on a ticket should be from the first message, not the replied-to one.

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1524]
Situation:

Ticket has multiple inbound messages, no outbound messages... let's say Mon, Tue, Wed.

On Thu, you reply to Wed (that message gets a 1-day reply time) and then reply to Mon (that email gets a 3-day reply time).  The ticket's first_response_time is set as 1 day, rather than 3.

**Comment by keith-chargeover** [comment]
👍 It would be very helpful to our team to have this _ticket_ reply time be what's expected.

**Comment by jstanden** [comment]
10.1.1: * [Tickets/Reports] On ticket records, the 'First Response' field is now computed as the time elapsed from ticket creation until the first outgoing message. Previously, the field had the same value as the first outgoing message's response time. This could be misleading if a new ticket had several inbound messages and the most recent was replied to first.
