### ISSUE TITLE
In 10.1.x, cancelling a reply warning still results in a draft

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1529]
WorkerA and WorkerB are both viewing a ticket.
WorkerA replies to the ticket.
WorkerB clicks reply, gets the warning about WorkerA's reply, and clicks 'Cancel'

At this point, there is an abandoned draft from WorkerB (and shouldn't be).  This appears to have been a change between 10.0.x and 10.1.x.

**Comment by jstanden** [comment]
This will be fixed in 10.2 with the 'recent activity' warning moving to pre-reply validators.

**Comment by jstanden** [comment]
Fixed in 10.2
