### ISSUE TITLE
Broken quote encoding when replying to some tickets?

### ISSUE THREAD

**Issue by fliespl** [jstanden/cerb#1536]
Hi Jeff!

Our CC team recently noticed that when they reply to some emails, encoding is broken in quote.

It doesn't happen on all emails - I was able to narrow it down to emails received with iso-8859-2 encoding (we use utf-8 configuration by default).

Not sure if it's a coincidence, but they didn't mention such behavior before recent upgrade to 10.1.1 (from 10.0 or 9.X - can't remember right now) and debian update from 9 to 10. Unluckily - it was done within two days apart.

When it comes to debian - I have made sure all php modules described in docs are installed.

Is it possible that something has broken down the line in code with converting encoding?

My gut tells me it's just coincidence and it was behaving that way before and maybe the scale was higher in the last days which made them wonder.

Thought I would ask you either way.

Thanks much!

**Comment by jstanden** [comment]
Hi @fliespl! Apologies for the delay here.

If you haven't already, can you send an example reproducing message source to team@cerb.ai so we can test with it?
