### ISSUE TITLE
Add ability for Mail Routing automations to set Custom Fields

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1540]
Client request is to set a particular custom field when a ticket is routed

**Comment by jstanden** [comment]
Any reason it couldn't be done on `mail.received` when checking `is_new_ticket` ?

The group/bucket would be set at that point and the ticket record would exist. It doesn't exist yet at routing.

We could likely support this if there was no other way.

**Comment by Hildy** [comment]
@jstanden - not sure; you're the one that said we needed it in the original (linked) ticket, but that need may have been obviated by later dev.

**Comment by jstanden** [comment]
k! I probably came to the same conclusion as above.
