### ISSUE TITLE
Bulk update custom fieldset multi-checkbox doesn't work

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1556]
Version 10.1.2 (Build 2021092901), Cerb Cloud

Custom Fieldset, Ticket type, owned by Cerb
Has a single custom field, type Multiple Checkboxes

When you bulk update a list of tickets to "set" one of the checkboxes on the custom field, it associates the fieldset with the ticket, but doesn't actually set the checkbox.  The checkbox can be set manually, and "unset" works from bulk update.

**Comment by jstanden** [comment]
Fixed in 10.1.4
