### ISSUE TITLE
Handle Outlook conditionals in HTML comments

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1559]
The HTML sanitization library is ignoring the Outlook conditional 'if' blocks (in HTML comments) entirely.  See linked ticket for specific code example.

**Comment by jstanden** [comment]
HTMLPurifier removes all IE conditions before it runs the `AllowedComments` directives. We'd have to preprocess this ourselves.

**Comment by jstanden** [comment]
https://stackoverflow.com/questions/5982364/is-there-a-html-conditional-statement-for-everything-not-outlook
