### ISSUE TITLE
[10.2] Undo bar doesn't go away when dismissed.

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1580]
When you close/delete one or more tickets from a worklist, you get the orange-ish undo bar at the top of the list.   After clicking '(dismiss)', the text disappears, but the orange-ish bar itself does not.

Undo bar, post close:
![image](https://user-images.githubusercontent.com/64052/149140997-49ab3153-e70a-448c-81a6-1d993148293b.png)

Undo bar, post '(dismiss)':
![image](https://user-images.githubusercontent.com/64052/149141084-a1d7e85c-a324-45bc-b14b-61edf164d4d7.png)

While it seems to have been introduced at the same time as the dark-mode style changes, I've confirmed that it happens in either dar or light mode.

**Comment by jstanden** [comment]
I can repro this. It has to do with a change in DOM structure from removing jQuery classes. I'll fix it up

**Comment by jstanden** [comment]
Fixed in 10.2-rc1
