### ISSUE TITLE
[10.2 - Dark mode] The highlighting on "-show quote-" needs toned down

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1581]
It looks a little too bright for dark mode (confirmed that text/highlight color codes are the same between dark mode and light mode)

**Comment by jstanden** [comment]
Thanks! I'll get this cleaned up.

There are still quite a few colors hardcoded in `style` attributes throughout the code.

**Comment by jstanden** [comment]
Fixed in 10.2-rc1
