### ISSUE TITLE
[10.2 - Dark mode] Change button gradient from 45->15 to 75-45 (or so)

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1584]
The light mode buttons are a 30-point gradient, 15 off the background of pure white.
The dark mode buttons are a 30-point gradient, 15 off pure black... but the background is rgb(32,32,32), so the buttons kinda hide.  We should move the dark mode button gradient so it's also offset from the dark mode background.

**Comment by jstanden** [comment]
This was done in 10.2-beta
