### ISSUE TITLE
Characters not correctly shown/recorded to DB - Charset problem

### ISSUE THREAD

**Issue by ScreamBE** [jstanden/cerb#1597]
Hello there,

We are working mainly in French and in this language there are a few special characters that are highly used (eg é, è, à, ç, ù, etc.).

"Randomly" we could see that when we clicked on "Reply" the quoted message was showing the initial message with broken charset:

![image](https://user-images.githubusercontent.com/8948341/151789882-31557f39-f0d0-42d7-9aba-348089525897.png)

After investigating I realzied that this also happens a lot to the "original_message.html" (which we actually do not really use)
original_message.html is correctly showing the message when opened as "Preview" inside Cerb but is broken when opened in a browser outside Cerb:
![image](https://user-images.githubusercontent.com/8948341/151790690-be1d103f-b366-4259-9d81-aaab3d22afa8.png)

Opening source code let us understand that somewhere Cerb made a convertion:

![image](https://user-images.githubusercontent.com/8948341/151792236-f2578142-dc03-4c2b-984a-8f396b75d692.png)

And indeed Cerb is converting characters (which makes absolutely sens. It is fine to have everything converted to the same charset otherwise some features wouldn't work correctly (eg searches or others):

https://github.com/jstanden/cerb/blob/a1497777d41b572e10c9dc6bb54b2c23843030dc/api/app/Parser.php#L1074

After that line, the problem is that the charset of the characters are converted to LANG_CHARSET_CODE  (= UTF-8 for us) while the heading still is : `<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">` as originally as it has never been changed.

--

How does that affect the text quoted in "Reply"?

Cerb is using the "plaintext" body when replying. For the mails where only the htmlbody was provided and no plaintext body, Cerb is using the htmlbody to create a plaintext body. 

https://github.com/jstanden/cerb/blob/a1497777d41b572e10c9dc6bb54b2c23843030dc/api/app/Parser.php#L1026

So my understanding is that when there are no plaintext body, Cerb is making a new one based on the converted characters that are still showing the old charset in the head/meta tag and I tested it and htmlToText function is still taking into consideration the original head/meta charset (and converting a new time what was already converted).

https://github.com/jstanden/cerb/blob/a1497777d41b572e10c9dc6bb54b2c23843030dc/libs/devblocks/api/services/string.php#L111

--

I hope the problem is clearely exposed?

I suppose (but I don't know the code enough or the possible impacts at other places of the code) that a solution would be to change the charset of the `<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">` of the source after we converted to LANG_CHARSET_CODE  

Hope this can help improve the beautiful work you guys are doing. I am available for additionnal information or test you would need 👍 

Regards,

**Comment by jstanden** [comment]
Thanks for the detailed report!

We've had one other bug report recently along these same lines and we couldn't reproduce it. But I suspect your `<meta>` charset encoding discovery is the key.

As you mentioned, we convert everything to UTF-8 internally. We also use UTF-8 in `htmlToText()` to build the new DOM tree, which should just be parsed as XML and not HTML (and ignore `<meta>` directives). But obviously something is going on here and we'll find it.

I'll work to reproduce this today and get a patch out.

I'll update this issue shortly.

**Comment by jstanden** [comment]
I reproduced the corrupt plaintext encoding issue with this message source:

```
From: customer@cerb.example
To: support@cerb.example
Subject: encoding problems
Content-Type: text/html; charset=iso-8859-1

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>
This is the body with:
À	Á	Â	Ã	Ä	Å	Æ	Ç	È	É	Ê	Ë	Ì	Í	Î	Ï
à	á	â	ã	ä	å	æ	ç	è	é	ê	ë	ì	í	î	ï
</body>
</html>
```

If I remove the `<meta>` header and re-parse it, everything works as expected.

You were right. A patch is on the way.

**Comment by jstanden** [comment]
You can try this patch:

```
Index: libs/devblocks/api/services/string.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/libs/devblocks/api/services/string.php b/libs/devblocks/api/services/string.php
--- a/libs/devblocks/api/services/string.php	(revision ad365b5af2b4d5c9e6b2a56951bddf5c6c762111)
+++ b/libs/devblocks/api/services/string.php	(date 1643688455755)
@@ -263,7 +263,9 @@
 		
 		libxml_use_internal_errors(true);
 		
-		$dom->loadHTML(sprintf('<?xml version="1.0" encoding="%s">', LANG_CHARSET_CODE) . $str);
+		$str = mb_convert_encoding($str, 'HTML-ENTITIES');
+		
+		$dom->loadHTML($str);
 		
 		$dom->normalizeDocument();
```

**Comment by ScreamBE** [comment]
Worked great 👍

What about the original_message.html ? the "wrong" meta (with iso-8859-1 instead of the UTF-8) is still used there making the file original_message.html (for anyone who use it) showing incorrectly the characters.

**Comment by jstanden** [comment]
Sure, we can handle the `original_message.html` attachment too.

We optimize those HTML attachments for display in the browser; so we pre-convert them to UTF-8 rather than doing that every time they're viewed.

As you mentioned, by leaving the `<meta http-equiv="Content-Type">` header in the file and later viewing it directly, we're misinforming the browser (and libxml) on the encoding after we've converted the bytes to UTF-8. When viewed inside Cerb, we remove the `<head>` section and only show the `<body>` fragment, so UTF-8 works fine.

So we'd either need to convert the attachment to HTML entities instead (always 7-bit ASCII) and remove the meta header; or we'd need to rewrite the meta header to use `charset=utf-8` (and add it when it doesn't exist).

In either case, we need to process the HTML as DOM instead of just converting the bytes as a string.

In recent versions of Cerb we have a cache for HTML messages (since they could be stored in S3); so it would also be possible now to just leave the encoding alone on HTML attachments, convert them to UTF-8 at display time, and cache that output for a day.

I'll experiment with the options.

In the meantime, if you really needed to work with an HTML attachment externally, you can save it, edit as UTF-8, and update the meta header.

**Comment by jstanden** [comment]
I have a patch going through testing for the HTML attachments. We now replace the 'Content-Type' meta header after converting the content to UTF-8.

In the future we may preserve the original encoding, but the attachments exist for display in Cerb.

If you need the raw message sources, you could have a copy forwarded to a second mailbox for storage. Something like Gmail will also archive a copy even when we issue a `DELE` on a POP3 connection.
