### ISSUE TITLE
When Custom Fields are deleted, we need to purge worklist filters, too

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#16]
Create a ticket custom field (e.g. picklist "Priority", with values "High", "Medium", and "Low").  Create/modify a worklist (with internal filters) to only show tickets with no priority set on them; verify that this list works.  Delete the Priority custom field, go back to the worklist, and note that it's now broken (and has a filter of " is null").

**Comment by jstanden** [comment]
I did a stopgap for this in 7.3.1 by just ignoring filters on missing custom fields, but I need to add this to the sanitize() method of abstract views to clean up the models.

**Comment by jstanden** [comment]
This is no longer an issue since you can only use queries in 9.0 (no internal filters).
