### ISSUE TITLE
Reopen dates not accepting strings they used to

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1604]
The date string-parsing of the reopen field (and I'd imagine any other date field that accepts text entry) has changed from 10.1 to 10.2.

The resume field allowed things like `2/17` and `02/17/22` and `2022-02-17` in 10.1.0, but none of those work in 10.2.0 (and the latter gets really strange; it gives me `Wed, 16 Feb 2022 02:22 pm`, which isn't any kind of even offset from now (nor a mathematical one)).

**Comment by jstanden** [comment]
Fixed in 10.2-beta
