### ISSUE TITLE
Unlinking task from project board column doesn't remove card

### ISSUE THREAD

**Issue by DaftBrit** [jstanden/cerb#1633]
When manually linking an existing task to a project board column, the task is displayed as a card in the given column, however after removing the link from the task (which was linked in error) the project board card still remains (even following a page refresh). Project board column item shows the task isn't linked and the correct link count however the card is still rendered.

Attached screenshot of card record showing no links to board
![Screenshot from 2022-03-15 10-48-24](https://user-images.githubusercontent.com/87314354/158361781-1096e6c0-e441-4cfc-ac4d-c63a64aa9020.png)

**Comment by jstanden** [comment]
Thanks for the report! I'll attempt to reproduce this now and I'll update the issue here with my findings.

**Comment by jstanden** [comment]
Yeah, I can reproduce this easily.

1. Add a new task card to a board column.
2. Open the task card peek popup.
3. Unlink the card from the board.

Expected:
The card disappears from the board column.

Actual:
Nothing changes in the board column.

Our current workflow is pretty clunky for removing cards from the boards. Now that project boards use sheets and toolbars in 10.x, we could enable selection there, and a column could have a simple 'remove' option in the toolbar, which refreshes afterwards.

For this particular issue, we just need to make sure that changing links on a card popup bubbles up the same change event we send when the record is edited+saved.

I'll get a patch for this into 10.2.2.

**Comment by jstanden** [comment]
This is fixed in development. We're doing a little more testing, then I'll push it to the `v10.2` branch on `cerb/cerb-release`. ETA should be tomorrow afternoon (Pacific).

**Comment by DaftBrit** [comment]
Thanks for the quick turn around @jstanden !

**Comment by jstanden** [comment]
The fix is pushed to `cerb/cerb-release:v10.2`

Thanks again!
