### ISSUE TITLE
Add new email address button doesn't come back after clearing autocomplete selection

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1639]
This scenario is probably at least a little generic, but the specific place I noted it was on the Add Worker dialog.  In the Email or Alternate Emails fields, if you select an autocomplete suggestion, the [(+)] button goes away[1].  If you then click the (x) to clear that selection, you get the autocomplete box back, but not the [(+)] button.

[1] secondary note; on Alternate Emails, since there can be multiple, the autocomplete box and [(+)] button shouldn't go away, ever.

**Comment by jstanden** [comment]
Fixed in 10.2.3
