### ISSUE TITLE
Feature request: Custom ticket statuses

### ISSUE THREAD

**Issue by dransome** [jstanden/cerb#1687]
We are evaluating Cerb but a big gap for us is how to gather the following reporting metrics:

* Amount of time a ticket waits in a queue for attention (not just the initial time to first reply, but also time from a customer's followup to when an agent responds)
* Amount of time actively worked on a ticket (we're aware of the time tracking feature for this, but it seems too manual - easy to forget to click start, or stop, and then the metrics become meaningless)
* Total ticket time until closed (you already have this one)

If we could define a few additional ticket statuses, it looks like we could gather this data via the activity log. 

For example:

- New: initial state of a ticket
- **In Progress: agent is actively working on the ticket**
- Waiting For (customer) Reply: agent has finished working on the ticket; awaiting customer input/confirmation
- Open: Customer has reopened the ticket and is awaiting attention (like "New" but for an existing ticket vs. a new one)
- Closed - Resolved: Issue was solved
- Closed - Unresponsive: Customer stopped responding

With these states, we could then map the amount of time each agent spent working on each ticket (the amount of time between In Progress -> any other state), and the amount of time a ticket spends "open" but not actively worked on (New -> In Progress, or Open -> In Progress).

_(We could then, I presume, set up a bot to only allow each agent to have 1 ticket marked as "In Progress" at once? That way we don't count their time utilisation multiple times over, since in reality each person can only really do 1 thing at a time)_

Is it within your plans to expand the range of available ticket statuses (or allow custom defined states) to facilitate the use case outlined above?

**Comment by Hildy** [comment]
Outgoing messages already track response time, so the built-in reporting should cover the average response times you're looking for, Damien.

The 'status' field doesn't have other options, but you can certainly have a custom field that tracks 'Ticket State' and use the options you've outlined above.  I don't think I see anything in what you've requested that wouldn't be possible with automations / bots.
