### ISSUE TITLE
Move cursor to end when replying in Twitter

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1688]
Customer reports that with 10.3, when replying to a tweet, the cursor is placed at the beginning of the text area (before the inserted username).  In 10.2.x, the cursor was at the end of the text area and you could immediately start typing after hitting reply.

There is a reported JS error in the console, which may be the cause:
`Uncaught SyntaxError: Unexpected token ‘&’ — appendChild`

**Comment by jstanden** [comment]
Fixed in 10.3.1
