### ISSUE TITLE
Ubuntu 22.04 install guide does not meet mailparse requirement

### ISSUE THREAD

**Issue by starchy** [jstanden/cerb#1701]
Hi,

Following the guide at https://cerb.ai/guides/installation/ubuntu/ results in `php8.1-mailparse` package `3.1.2+2.1.7~dev20160128-7` being installed. After starting cerb 10.3.4, the environment check page reports "PHP Extension (MailParse)... Error! Cerb requires the 'mailparse' extension version 3.1.3 or later" and refuses to continue.

**Comment by jstanden** [comment]
The new install guide uses Ubuntu 23.04 and avoids this issue:
https://cerb.ai/guides/installation/ubuntu/

The Docker Compose example also avoids it.
