### ISSUE TITLE
[Feature Request] Add a date-type column to sheets

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1707]
It'd be handy to have a specific date-type column for sheets that would automatically give you the prettytime display, tool-tip real time, date sorting, etc.

**Comment by jstanden** [comment]
There is a `date:` column type for sheets:
https://cerb.ai/docs/sheets/#date

It does lack a tooltip option, which should be easy enough.

**Comment by jstanden** [comment]
Will handle on #1708
