### ISSUE TITLE
Comments from Edit card do not send @mention notifications

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1743]
Repro'd in 10.4.2 (Cerb Cloud).  (Could not repro in 10.3.11.)

Comment using 'comment' button with @tag sends notification.
Comment using 'edit' button with @tag and no other changes does not send a notification
Comment using 'edit' button with @tag and status change sends status change notification, but not comment notification.

![image](https://github.com/jstanden/cerb/assets/64052/cc54797d-906d-4f0e-bdef-19b52749c64f)

**Comment by jstanden** [comment]
I can reproduce this. Investigating

**Comment by jstanden** [comment]
Fixed in 10.4.4
