### ISSUE TITLE
Clicking 'Cerb' in log entries gives an error

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1744]
If you click the 'Cerb' link, it reports resource not found

![image](https://github.com/jstanden/cerb/assets/64052/1225cd23-ed71-4b9a-ae4a-0381bc55c62d)

![image](https://github.com/jstanden/cerb/assets/64052/01adf18f-dc92-438f-94b7-adc06b7a8157)

**Comment by jstanden** [comment]
Fixed in 10.5
