### ISSUE TITLE
[API] Search on Contexts (Custom Fields)

### ISSUE THREAD

**Issue by abrenner** [jstanden/cerb#177]
Problem: When trying to retrieve information about a custom field, a developer has to search on all contexts. There presently no filters to narrow down the results from the API thus leaving the developer to perform application side filtering.

The old API call `GET /customfields/ticket` appears to be deprecated and no documentation exists for this, but offered this feature. 

Solution: Offer a search/filter option on `GET /contexts/list.json` so a developer is able to select what type of context they are looking for (for example `cerberusweb.contexts.ticket`) or and a specific list of custom fields (their names custom_3, etc.)

/adam

**Comment by jstanden** [comment]
This should be fixed in the 8.2 update with custom fields having their own record type, and the ability to do abstract `/records/` operations in bots/packages/API.

**Comment by jstanden** [comment]
You can search custom fields in the `/records` API now: https://cerb.ai/docs/api/modules/records/#search
