### ISSUE TITLE
New worker not being added to correct role

### ISSUE THREAD

**Issue by nicholsk18** [jstanden/cerb#1770]
When you create a new worker, they dont seem to be added to itemized role.
After the worker is created if you hit save again it seems to add them to that role.

When creating a new worker, roster updates happen before group membership is set
https://github.com/jstanden/cerb/blob/10.4.7/features/cerberusweb.core/api/uri/profiles/worker.php#L190
https://github.com/jstanden/cerb/blob/10.4.7/features/cerberusweb.core/api/uri/profiles/worker.php#L269

so if your role is filtered by group they dont have any of those permission till you update that worker or role again.

Im not sure if it would break anything else, but adding worker to the group before updating roster should resolve this issue

**Comment by jstanden** [comment]
Thanks for reporting the bug, @nicholsk18!

I'll get this cleaned up. :)

**Comment by jstanden** [comment]
Fixed in 10.4.14
