### ISSUE TITLE
When you change a KB category parent, the Article links to their Top category need updated

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1776]
Rearranging KB Categories can leave KB Articles pointing to the wrong (or non-existent) Top Categories (which gets used for determining display in the portals).  `kb_article_to_category.kb_top_category_id` needs updated when category structure changes.

**Comment by jstanden** [comment]
This is fixed in 10.4.10.

When a KB category has a change in parent, we now recalculate the root KB category for all article<->category links.
