### ISSUE TITLE
Deleting a group needs to also address signature ownership

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1787]
This may apply to other "owned" objects as well, but when an email signature is owned by a group, and that group is deleted, the signature can be ... orphaned.  It has no owner (displayed in the card), and also has no way to clear the owner (in the db) and set a new one.

Another option might be to just have the card / edit have the ability to clear an invalid owner, but I suspect the problem applies to other owned objects as well.

**Comment by jstanden** [comment]
Fixed in 10.4.15
