### ISSUE TITLE
[Feature Request] Add recipient search/listing from Ticket Web-API

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#203]
Customer would like to be able to get a list of the participants on a ticket via the Web-API, and there does not appear to be any way to do that at this point in time.

**Comment by jstanden** [comment]
@Hildy It's not documented anywhere (and needs to be), but you can expand `requesters` and `requester_emails` on ticket records.

**Comment by abrenner** [comment]
@jstanden and @Hildy thanks for looking into this. I was the customer that requested this.

Expanding requesters allows me to view a list of participants along with their contact_id if it exists.

However, what about full CRUD support? I would like to add and remove participants to a ticket.

thanks,
-Adam

**Comment by jstanden** [comment]
@abrenner Sure, I'll add a new issue for CRUD on participants if that's not filed yet. :)

**Comment by jstanden** [comment]
https://github.com/jstanden/cerb/issues/217
