### ISSUE TITLE
Changes to worklist titles don't propagate to existing worker_view_model records

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#259]
Scenario is a shared page/tabs/lists.  Multiple workers have loaded the tab.  One then changes the title of a worklist on that tab, and the change is reflected for the worker who initiated the change (and any who first view the worklist post-change), but not for any other workers who had previously viewed that list.

**Comment by jstanden** [comment]
I can't reproduce this, but I did observe it having happened in a client environment. Something must be interrupting the process; so we can try to make it more efficient.

**Comment by jstanden** [comment]
This should no longer be an issue with the changes in 8.3.
