### ISSUE TITLE
[Bots] Bot action for calculating a time elapsed given start, end, and a calendar

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#272]
> Our director recently asked: could we use the << first-solution >> - time
> from all tickets, to create some statistics and prove our reaction-time ?
> what if: a client write at 4 :55pm -> we close at 5 pm a didn't find a
> solution and didn't write back (working during 5 minutes at the ticket)
> Next morning, 8am we start work, at 8:05am we found the solution and write
> back. (another 5 minutes at the ticket)

Basically, you'd need a calendar of business hours.  Then bots would need a new action to calculate a time elapsed given a start date, an end date, and a calendar's availability.

That would be really useful.

**Comment by nbeernink** [comment]
I'd be really interested in this as well.

**Comment by jstanden** [comment]
<img width="956" alt="screen shot 2017-07-03 at 7 10 52 pm" src="https://user-images.githubusercontent.com/63288/27812395-661daa56-6023-11e7-9c0b-87896164b744.png">

**Comment by jstanden** [comment]
Implemented in 8.1
