### ISSUE TITLE
[worker-settings] make remembering last used from-address a worker preference

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#282]
We have several from-addresses configured in Cerb of which we use one primarily. The problem is that we occasionally have to send just 1 message from another address. Since Cerb remembers the last used from-address and sets that from-address for the next message sent. 

If you overlook this, you need to correct yourself in the next mail due to the wrong address and signature being used.

Default to off would be great for us. :wink:

**Comment by jstanden** [comment]
In 8.0.5 there's a feature to set the default compose sender on a worklist, which ignores the default behavior.

**Comment by nbeernink** [comment]
That seems fair enough. But how does that work when composing from a search? :)

**Comment by jstanden** [comment]
In 8.x, compose first uses any singular group filter on the worklist. Then it uses the previous selection. So what a search popup does would depend on those factors.

I agree that it would be nice to have more control over the default.  A one-time worker preference is probably better than something that constantly changes.

**Comment by jstanden** [comment]
This isn't an issue in 10.x since you can use the draft generator example rather than compose, and default all properties.

https://github.com/cerb/cerb-release/discussions/16
