### ISSUE TITLE
[Bots/Behaviors] In 'Before sending worker message' events, allow separate modification of the 'sent' and 'saved' versions of the message

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#283]

**Comment by iammattmartin** [comment]
This would be a good feature!

**Comment by iammattmartin** [comment]
On thinking about this further, most cases would be on before sending message from worker, so it would be useful if you could set a flag on the prepend and append to not save those parts in the saved message but do send them.

Allows for wrapping the ticket content up for email but only storing the real "useful" content in the database.

**Comment by jstanden** [comment]
https://twitter.com/mattmartincouk/status/903052707736539136

**Comment by jstanden** [comment]
Implemented in 8.1.1
