### ISSUE TITLE
[Mail] Allow outgoing mail from specific workers to be queued for a given review period

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#286]

**Comment by iammattmartin** [comment]
*To allow the messages to be caught before they are sent. i.e a 60/120 second hold at which time you could edit or delete the message before it leaves.

(Instead of say a manual audit queue - although I suspect both could be achieved at the same time)

**Comment by jstanden** [comment]
We've had trouble scheduling this compared to higher priority features like SSO (OIDC/SAML), roles refactor, package library, utf8mb4, etc. Those changes touch potentially dozens of feature requests.

Bots can already schedule mail for future delivery. The mail queue is designed for this, and it's how broadcasts work. They're just drafts that have been converted to queued mail with a future delivery date.

The change here is optionally providing a future delivery date field on the reply form, and allowing a bot behavior to override/force that. Every reply would turn into a queued draft that could be updated or cancelled before the delivery time.

**Comment by iammattmartin** [comment]
The latter would be good if added soon, obviously, it's something we've been trying to work around but means that some tickets don't go through the check before sending and with some new starts quality often needs to be checked.

Tentatively, any chance of this year as it has been open coming up to 2 years.

**Comment by jstanden** [comment]
Hi Matt!

I put a little more time into this during 9.3 development. You can schedule a "send at" time when replying. That can be overridden by bot behaviors on a per-worker/per-group basis, etc.

That converts the draft to a scheduled delivery. It shows up in the ticket timeline just like drafts do. At the scheduled time it would be sent and converted to a proper message.

We need to make a few other improvements to handle your use case:

* Scheduled messages should be editable as drafts by the sender and admins.

* The reply `#commands` (like `#comment`) should be processed by the mail queue.

Those tweaks are minor and then we could launch this feature.  It would be useful in sales to be able to schedule messages for the start of a contact's next workday (e.g. late on a Friday).

**Comment by jstanden** [comment]
@iammattmartin Hey Matt! This feature is finally good to go for the 9.4 release.

We've done a ton of work on drafts UX; including the ability to schedule delivery of drafts when composing/replying. You could override the 'send at' time with a bot behavior conditionally for specific workers. A manager/admin could review the draft, add sticky notes as commentary, etc. Scheduled drafts can be easily reverted back to editable drafts (by the author or admins).

Bots can generate drafts in the same way, where workers can approve them or make the necessary changes. A really handy aspect of that is those draft suggestions can include anything: to/cc/bcc, subject, content, ownership, group/bucket, custom fields, links, status/reopen, attachments, etc. Right now, the alternative of 'snippets' are limited to a few paragraphs to inject into the body.

We're also considering making 'review' an explicit state of drafts, where they could be: in progress, in review, or published (scheduled/sent). Workers who lack 'send' permission in their roles (or for some groups), or who are non-members of those groups, could have their outgoing messages require approval by a group manager/member. That should be a really clean way to handle what you've been looking for.

**Comment by jstanden** [comment]
Implemented in 9.4
