### ISSUE TITLE
[Mail] Allow dynamic sender addresses

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#287]
> (side note: Has cerb ever thought about using plus addressing i.e
> hashid+department@domain.com to identify replies instead of using
> subjects? We’ve seen increase in clients not keeping mail IDs and
> completely trashing ticket threads).

Generally, we rely on the `Message-Id:` and `In-Reply-To:` headers, and not subjects. Reference numbers exist in the subject as a fallback, but you'll notice that we don't even use that ourselves.

Everything we'd need for plus addressing on the incoming side should be possible already.  You can receive mail for any address without pre-configuring it.  A bot on the 'Before mail is accepted' event could find the current thread based on a token in the email address and synthesize the 'In-Reply-To:' header before Cerb's parser runs.

For outgoing mail, the missing piece would just be the dynamic outgoing email address.  That could just be an option on the 'sender address' record, which would be simple enough.

**Comment by nbeernink** [comment]
I see this too when communicating with zendesk-based helpdesks.

**Comment by jstanden** [comment]
There has been no demand for this from enterprise clients.
