### ISSUE TITLE
[Mail] Allow defined subject on "Send email to recipients".

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#298]
This is allowed on send email but that requires a from address set which does not work ideally when used in some situations.

When you use "Send email to recipients" it uses the group/bucket email which is better as that is automatic but the option to change the subject isn't possible.

**Comment by jstanden** [comment]
It wouldn't be difficult to send a different subject in the email. However, the same code currently replaces the overall ticket subject when any reply changes it. That's consistent with the expected UI behavior, but not what we'd want to happen here.

We'd need a different option for the email subject independent of the ticket.

**Comment by jstanden** [comment]
This would use `mail.transactional` in automations in 10.x. Bot behaviors are being phased out by 11.0.
