### ISSUE TITLE
[Worker/Mentions] double notifications due to same-mention name

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#300]
I don't know how, but somehow it was possible on our desk to have two workers with the same mention name, generating the same notifications for each worker. 

I tried to reproduce the issue by creating another worker with the same mention name, but in that case there is a nice error that tells me the mention name is already in use. Same for trying to edit the name.

We've been running the same cerb 7.2 version for a while now and the workers that have the mention names were never part of an upgrade. They've both been made while on 7.2.

**Comment by jstanden** [comment]
Strange.  The 8.1 update enforces the @mention uniqueness at a low-level now (`DAO_Worker::update()`), so this shouldn't be possible going forward.

**Comment by nbeernink** [comment]
Thanks for checking Jeff! :)

**Comment by jstanden** [comment]
Sure thing :)
