### ISSUE TITLE
[Bots/Behaviors] Load participant record info from a ticket behavior

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#307]
> I can’t even seem to access the contact the ticket is assigned to but
> I guess this is because there is no “master” ticket owner for a
> customer - it could be many people?

There could be multiple participants.  But in this case, it sounds like you just want the initial sender.

If you opened the ticket for them, you could read out the participant info.

You can do something like:

~~~
{{ticket_requesters|json_encode}}
~~~

Which shows you object info for each participant.  Their first names would be:

~~~
{{ticket_requesters|first.name|split(' ')|first}}
~~~

The better way to get at their true contact details would just be to add/set a behavior list variable.

1. Edit the behavior.

2. In Variables, add a List->Email Addresses named 'Participants'

3. Save the behavior

4. In the behavior tree, add a new action at the top and 'Set (variable) Participants'

5. Use a quick search like:
~~~
id:[{{ticket_requesters|keys|join(',')|default('-1')}}]
~~~

6. Save the action.

7. You can then refer to any participant field (with key expansion) with:

~~~
{% set participant = var_participants|first %}
Hi {{participant.contact_first_name}},
~~~

I'll see about changing how the 'ticket_requester' placeholder behaves so it can just return those dictionaries itself as part of the results (a new property called 'dictionary' or 'model').  That would save all of those steps.  That placeholder originally existed for the API where the extra key expansion didn't make sense (the request would have already downloaded), but in bots/snippets it would be very useful.

**Comment by jstanden** [comment]
This is possible with the new records API in 8.2.2.

**Comment by iammattmartin** [comment]
Are you able to give an example of how to do this in 8.2.2 @jstanden?

**Comment by jstanden** [comment]
Use the **Record -> Search** action on email addresses with a query like `id:[{{ticket_requesters|keys|join(',')]`. Those will be dictionaries, so you can expand their contact info, etc.
