### ISSUE TITLE
[Connected Services/Calendars] Add a CalDAV service for synchronizing events into calendars

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#318]
To avoid duplication of an already existing calendar system, could there be scope to automatically pull availability from CalDAV set per user.

Additionally, being able to set a standard schedule for a worker, i.e Mon-Fri, 9am-5pm and the system assumes they are working unless they have an entry otherwise.

**Comment by jstanden** [comment]
@mattmartincouk On the latter part, you can create an 'Office Hours' calendar.  Then on the worker's calendar enable synching events, select Calendar as the source, and pick that shared Calendar.

**Comment by iammattmartin** [comment]
Thanks for the tip re cals @jstanden. I think the reason I got confused about that was due to the recent issue if tickets not finding the time properly so didn't think it would work right.

Might see if we can make something that syncs in with caldav, maybe both ways - that'd be sweet and will happily contribute :)

**Comment by jstanden** [comment]
This will be a lot easier to implement as of 9.1 because we have the new "connected services" layer. DAV-based sources would just be a new service.

I need to set up a staging environment that I'd be importing data from, but the rest of it should be easy enough.

**Comment by jstanden** [comment]
This is done in 10.3 with VObject support (vCard, iCalendar/ICS, etc).
