### ISSUE TITLE
popup menus truncate at the top of a worklist

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#320]
So that title's a little confusing, maybe, but here's the scenario.  Click Export on the top of a ticket worklist, scroll so the export fields are at the bottom of your browser window, and hover over "Owner".  Because the list is too long to go down, it goes up, but is truncated at the top.

![image](https://user-images.githubusercontent.com/64052/28696438-69ac2a2e-72ea-11e7-9116-68ffa817044d.png)

**Comment by jstanden** [comment]
I can't repro this in dev on 8.2, but it appears to repro in production on 8.1.3.  Same browser + OS.

**Comment by jstanden** [comment]
Strange. It looks like if the subtotals sidebar is enabled then it overflows downward. If subtotals are closed then it overflows upward and truncates.

At least I can repro it in dev now.

**Comment by jstanden** [comment]
Fixed in 8.1.4
