### ISSUE TITLE
8.0.4 plugins don't install 

### ISSUE THREAD

**Issue by lingwooc** [jstanden/cerb#321]
Version 8.0.4 (Build 2017072501) running on apache/php7 in alpine in docker. 

**Behaviour**
Go to plugin library and click "download and install" twice on any plugin.
There is a bit of a "flash" then nothing more.

**Expected behaviour**
Plugin would ask to be enabled and would show as installed

There is nothing in the storage/plugins folder. Permissions look ok as cache is working.

Apache error log shows:
[Mon Jul 31 14:58:59.833813 2017] [php7:error] [pid 117] [client 10.8.2.3:61102] PHP Fatal error:  Uncaught Error: Call to a member function getStoragePath() on null in /app/features/cerberusweb.core/api/uri/config/plugins.php:90\nStack trace:\n#0 /app/features/cerberusweb.core/api/uri/config.php(74): PageSection_SetupPlugins->showPopupAction()\n#1 /app/features/cerberusweb.core/api/plugin.classes.php(74): ChConfigurationPage->handleSectionActionAction()\n#2 /app/libs/devblocks/api/Engine.php(677): ChPageController->handleRequest(Object(DevblocksHttpRequest))\n#3 /app/api/Application.class.php(289): DevblocksEngine::processRequest(Object(DevblocksHttpRequest), true)\n#4 /app/ajax.php(95): CerberusApplication::processRequest(Object(DevblocksHttpRequest), true)\n#5 {main}\n  thrown in /app/features/cerberusweb.core/api/uri/config/plugins.php on line 90, referer: http://10.8.2.2/index.php/config/plugins/library

I will experiment later to with 7.x.x see if the version is the problem.

**Comment by jstanden** [comment]
Where you're getting the error, Cerb is loading the plugin manifest from the cache (built from the `plugin.xml` files).

As you mentioned, the `storage/plugins/` directory is empty.  The plugin should have been downloaded and extracted there.

What's the ownership/permissions on the `storage/plugins/` directory?  The cache is in `storage/tmp/`, so it may be set differently.

I assume the Docker container has public network access, since you were able to list the available plugins.

Is the PHP 'zip' extension installed?  If not, you could try that and we'll see if it's a PclZip (pure PHP fallback) issue.

Is the `suhosin` extension installed?

**Comment by lingwooc** [comment]
Good call! php7-zip was not installed. It is now and it has all started working. It's always a bit of a hazard with docker that you only have what you explicitly install!

Perhaps that should be a dependency for the installer, or the error message could point the user in the right direction?

Thanks for the help!

**Comment by jstanden** [comment]
Sure thing!

The 'zip' extension is preferred, but it's not required.  We fall back to PclZip as a pure PHP library, but it sounds like there's an issue with that somewhere in your stack.  I'll file a new issue to check it out.

Thanks for the report. :)

**Comment by lingwooc** [comment]
These are the docker files with the issue. You just need to put a folder at ./cerb with cerb in it and an empty folder at ./mariadb and set the mysql user/pass, it should be good to go. If you add php7-zip to the second ``RUN apk`` line then it will work.

Dockerfile
```
FROM alpine:latest
LABEL Description="A Simple apache/php image using alpine Linux for Web Apps"

# Install gnu-libconv required by php7-iconv
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so

# Setup apache and php
RUN apk --update add apache2 php7-apache2 curl \
    php7-json php7-phar php7-openssl php7-pdo_mysql php7-curl php7-mcrypt php7-pdo_mysql php7-ctype php7-gd php7-xml php7-dom php7-iconv php7-mysqli php7-mbstring php7-session php7-mailparse php7-simplexml php7-imap \
    && rm -f /var/cache/apk/* \
    && mkdir /run/apache2 \
    && mkdir -p /opt/utils

EXPOSE 80

ADD start.sh /opt/utils/

RUN chmod +x /opt/utils/start.sh

CMD /opt/utils/start.sh
```
start.sh
```
#!/bin/sh

# Enable commonly used apache modules
sed -i 's/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/' /etc/apache2/httpd.conf
sed -i 's/#LoadModule\ deflate_module/LoadModule\ deflate_module/' /etc/apache2/httpd.conf
sed -i 's/#LoadModule\ expires_module/LoadModule\ expires_module/' /etc/apache2/httpd.conf

sed -i "s#^DocumentRoot \".*#DocumentRoot \"/app/$WEBAPP_ROOT\"#g" /etc/apache2/httpd.conf
sed -i "s#/var/www/localhost/htdocs#/app/$WEBAPP_ROOT#" /etc/apache2/httpd.conf
printf "\n<Directory \"/app/$WEBAPP_ROOT\">\n\tAllowOverride All\n\tphp_admin_value upload_tmp_dir /tmp\n</Directory>\n" >> /etc/apache2/httpd.conf

if [ -z "$WEBAPP_USER_ID" ]; then
    chown -R apache:apache /app
else
    # Override apache user under which apache runs its child processes with the one provided
    # Useful for running container in development mode enabling live code modification
    runApacheAsUser=webapp
    apacheConfigPath="/etc/apache2/httpd.conf"
    addgroup -g $WEBAPP_USER_ID $runApacheAsUser
    adduser -D -H -g "webapp user" -G $runApacheAsUser -u $WEBAPP_USER_ID $runApacheAsUser
    chown -R $WEBAPP_USER_ID:$WEBAPP_USER_ID /app
    sed -i "s/User apache/User $runApacheAsUser/" $apacheConfigPath
    sed -i "s/Group apache/Group $runApacheAsUser/" $apacheConfigPath
fi

httpd -D FOREGROUND
```
docker-compose.yml
```
version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=cerb
      - MYSQL_USER=xxxxxxx
      - MYSQL_PASSWORD=xxxxxxx
      - MYSQL_ROOT_PASSWORD=xxxxxxxxx
    volumes:
      - "./mariadb:/var/lib/mysql:rw"
  dte_cerb:
    build: .
    volumes:
      - "./cerb:/app:rw"
    ports:
      - "80:80"
    links:
      - db
```

**Comment by jstanden** [comment]
Thanks @lingwooc, that's incredibly useful.  I linked that on #326.
