### ISSUE TITLE
[Bot/Mail] - default - email or group lookup instead of fixed

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#339]
On "send email" the `(default)` email address uses the system default. This seems to differ from 
 `- default -` on a bucket which uses the main group email so similar reference, different behaviour.

"send email" is far more useful when sending auto responders, message rejections etc as you can change the from address, subject (instead of setting permanently to something else), even to: cc: etc.

Can this be improved by either allowing the (default) reference to use the group address that the bot is being run against or another option that looks up the current group email?

(or alternatively, allowing the "send email to recipients" to be more flexible in terms of subject and from address?)

**Comment by iammattmartin** [comment]
This improvement would also help with the Satisfaction bot being able to send from the group address and not the system address with a custom subject.

**Comment by iammattmartin** [comment]
Further to this, have discovered the From: Ticket Bucket in the drop down which appears is the answer but does not appear to work.

Is it relational to the bucket which then should use the "Send worker replies as" as set on the bucket?

I set that and it seems to use the default system email instead of the ticket bucket address.

Edit: This ("Ticket Bucket" placeholder) only appears some of the time. Sadly not everywhere (new message added to ticket) it is needed.

**Comment by iammattmartin** [comment]
Allowing this to pull correctly would then mean #298 isn't required because it'll allow subject changes when using the correct from (linked to group/bucket dynamically).

**Comment by jstanden** [comment]
https://twitter.com/mattmartincouk/status/903052707736539136

**Comment by jstanden** [comment]
Fixed in 8.1.1.  Events like 'New message added to ticket' now provide a 'Ticket Bucket' or 'Group' placeholder when available. Let me know if we missed any.

**Comment by iammattmartin** [comment]
I'm not entirely sure if this is working as reported, or maybe we've got our wires crossed.

http://scrn.at/E9bZK.png

Set to "Ticket Bucket" for the "Send Email" message on an outbound satisfaction bot email (on close) but it still only comes from the helpdesk default address/name.

Running 2017090201 so unsure if that should be expected or not.
