### ISSUE TITLE
[Mail /Templates] Template not obeyed on sub-buckets

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#347]
I have been testing templates and sub-buckets.

When the mail goes from the Inbox on a group, the template set on the outbound address is obeyed. The reply uses - default - and this is styled as expected.

When a ticket is in a sub-bucket with the same - default - set, it should then do the same as above. Except it does not. It appears similar but some of the styling is lost. The outbound address is the same (set to - default - )

I have checked it is not picking up the system default template which isn't the case (I made all text appear red if that was used).

If I specifically set the bucket to the template, the style is alike but that should not need to be done because the outbound address is correct (and it has part of the style).

![screen shot 2017-08-13 at 8 31 30 pm](https://user-images.githubusercontent.com/15971590/29252856-b92df4ea-8066-11e7-8159-7b702774c4e3.png)

Left is the expected style, right is not.

Left occurs when sent via the Inbox (set to - default -) or when the sub-bucket is specifically set to the template it should inherit.

Right is when the sub-bucket is set to - default - and appears to do something strange.

**Comment by jstanden** [comment]
This should no longer be an issue in 8.2.  The cascading of sender/signature/template was simplified to bucket->group, and reply-to (sender) addresses no longer exist as a separate record type.  The migration copies the group inbox defaults to the group itself.
