### ISSUE TITLE
Some prefilter criteria are broken

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#357]
On the 'before new incoming message is accepted' event, trying to use the Message attachment name or Message attachment MIME type criteria in an outcome is un-helpful, as there are no comparison options.

![image](https://user-images.githubusercontent.com/64052/29434237-09cda5f6-8357-11e7-9ce2-c79595b72509.png)

**Comment by jstanden** [comment]
Fixed in 8.0.6
