### ISSUE TITLE
[Bot/Webhook] Webhook calls bot even if disabled

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#359]
We have a webhook that calls a bot. Whilst testing, we disabled the bot which we would have thought would not run the webhook.

It seems that the webhook can run the actions in the bot regardless of the bot status being disabled.

I would imagine this is not the expected behaviour.

**Comment by jstanden** [comment]
Good catch! We'll get that cleaned up.

**Comment by jstanden** [comment]
Fixed in 8.1.1
