### ISSUE TITLE
File upload on HTML templates doesn't have focus

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#36]
I think...

In Setup -> Mail -> HTML Templates, in an individual template card, if you click one of the other things like insert a link or link to an external image, then 'esc' closes that popup.  If you click the upload a file icon, then 'esc' closes the *parent* template popup first, then a second 'esc' closes the file dialog (should be the other way 'round)

**Comment by jstanden** [comment]
I **can** reproduce this.

**Comment by jstanden** [comment]
Fixed in 7.3.4
