### ISSUE TITLE
[Mail/Relay] Relay HTML messages

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#361]
At the moment the email relay feature sends the plaintext with HTML as an attachment.

**Comment by iammattmartin** [comment]
Also, where possible, if the text worker email could be converted to use the HTML template when actually sent outbound. 

All mail from our desk will be HTML to use pretty templates but those sent via worker relay emails wouldn't then follow that design and look odd. Not a show stopper but some might get concerned at the format change.
