### ISSUE TITLE
Add Markdown style formatting to comments

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#362]
Customer request is for formatting abilities for comments (bold, bullets, etc), so making those Markdown enabled will allow that (and any other HTML formatting, as well).

**Comment by Hildy** [comment]
Filing it as a reminder, but when certainly isn't guaranteed

**Comment by jstanden** [comment]
I'm all for this. It should have been done a long time ago.

**Comment by jstanden** [comment]
Implemented in 9.4
