### ISSUE TITLE
[Bots] Expose "Parent Ticket" to "with this record"

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#372]
When trying to use snippets assigned to tickets from the pre-parse bot using the parent ticket, there is no option for just "parent ticket".

It knows this information because it allows you to pull other parts of the ticket down.

This would allow responses to use snippets and various other data from the ticket itself without having to duplicate responses to plain text.

![apqlr](https://user-images.githubusercontent.com/15971590/29631935-3092b4ba-8839-11e7-9b94-1e771d1a0254.png)

**Comment by jstanden** [comment]
Implemented in 8.1.4
