### ISSUE TITLE
Add a pre-close event to popups so we don't throw away edits on 'Esc'

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#375]
This is particularly an issue with Comment and Sticky Note popups; if you're typing a note and hit esc for some reason (leftover vi muscle memory?), it immediately closes the popup and discards what you were typing.  

We could, instead, check the form to see if anything has been entered, and then prompt with an 'Are you sure?' type of confirmation before closing.

**Comment by jstanden** [comment]
Implemented in 8.2
