### ISSUE TITLE
API reports that a ticket doesn't exist when the worker doesn't have access to it

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#383]
Instead of telling you that the ticket doesn't exist (when it's in a group your API keys aren't a member of), the error message should inform you that you don't have access to that ticket.

**Comment by jstanden** [comment]
This happens because the `GET` action uses `search` behind the scenes, and the group memberships are one of the filters. We'd need to switch this to `::get()` and reproduce the dictionary output of search to give a better error message.

**Comment by jstanden** [comment]
This hasn't come up again. Closing for now.
