### ISSUE TITLE
Allow non-to: to work the same as the to: field.

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#421]
There are instances where you want to put participants in a cc or maybe bcc context but not as to: i.e secondary user who should always get a copy but never be considered the main participant.

Currently, cc/bcc are one time only selectors and you'd have to re-add them at each reply. That is useful for one-time messages but often the copy needs to go to them each time.

Putting them as a main participant instead of a cc/bcc might not be suitable especially if you're linking a ticket to a user by the lone participant.

**Comment by jstanden** [comment]
This could be done with automations now.
