### ISSUE TITLE
Pre-parse behaviors write logs poorly

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#426]
This is actually something that cost me a lot of time in looking for a totally separate (user-caused) problem, but tracking it down was made quite difficult by this issue.

When a pre-parse behavior (from Setup -> Mail -> Filtering) sets the value of a fieldset on a ticket, the log entry claims "Cerb" did it, and the link from Cerb is a blank card popup.
![image](https://user-images.githubusercontent.com/64052/30353487-0e461c6a-97db-11e7-94db-006a2b048e7f.png)

When it's done from a normal behavior, the bot and behavior are properly linked there.
![image](https://user-images.githubusercontent.com/64052/30353479-fd1f0b68-97da-11e7-8e62-8716e2235875.png)

It also records a bad log entry on the fieldset (when it's done from the pre-parse filters).
![image](https://user-images.githubusercontent.com/64052/30353496-23636f1c-97db-11e7-9717-a8fec595667c.png)

**Comment by jstanden** [comment]
This shouldn't be an issue in automations. Since we've phasing out behaviors, I'm going to close this one.
