### ISSUE TITLE
Fieldset Owner Label is too aggressive in escaping

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#427]
This may be a poor description / title, but I have a Role named "Itemized, but still nothin'" (with an apostrophe at the end).  When that Role is the owner of a Custom Fieldset, and that fieldset is displayed on an object, the ownership shows an HTML code instead of the apostrophe.

![image](https://user-images.githubusercontent.com/64052/30385751-f3db7c30-985c-11e7-814f-5c7745271eeb.png)

**Comment by jstanden** [comment]
Fixed in 8.1.3.

That one was a pain to spot.  In Smarty, `{{$var}}` escapes output. With the auto-escape plugin, it then becomes double escaped. The `{{...}}` syntax is from Twig.
