### ISSUE TITLE
Use of "Ticket Bucket" in From for Send Email does not work

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#432]
When selecting Ticket Bucket to use that email address when sending email from a bot, it still only uses the default helpdesk email (global) instead of the bucket itself.

Linked #339, with an image showing current use. (Satisfaction bot sending email from current group/bucket (Inbox))

The name and email address it is send from both match the global address instead of the group/bucket.

**Comment by jstanden** [comment]
Properly fixed in 8.1.3
