### ISSUE TITLE
Keyboard modifier for peek to open the edit dialog instead

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#433]
The thought here is to have something (maybe like a ctrl-click) open the edit dialog instead of the peek dialog.  A keyboard shortcut on peek that'd switch it to the edit dialog (closing the peek at the same time) could also work, perhaps.

**Comment by jstanden** [comment]
Implemented in 9.4. You can hold `<Cmd>` or `<Shift>` when left clicking a peek popup to open in edit mode.
