### ISSUE TITLE
Ticket links to non-existent tickets report NaN / undefined error

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#435]
Reported by a user on 7.3.x (I believe), confirmed by Dan H on 8.1.1.

Scenario:
TicketOne predates TicketTwo
Ticket Two has one or more time tracking entries
TicketTwo is merged into TicketOne

At this point, prior to the maintenance cleanup of TicketTwo, the link in the time tracking entry's Log pulls up the TicketTwo card, but with no messages (as sortof expected).

Once TicketTwo is purged from the db via maintenance, clicking the link (to TicketTwo) in the Log tab of the time tracking entry gives you a peek with no info and a "Message NaN of undefined" label:

![image](https://user-images.githubusercontent.com/64052/30603239-c5521d92-9d1b-11e7-8f2f-1c2f81c72b13.png)

**Comment by jstanden** [comment]
Fixed in 8.1.3
