### ISSUE TITLE
[Validation] Validation issues with 32-bit PHP (>PHP_INT_MAX)

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#437]

**Comment by jstanden** [comment]
Client writes:
> Another similar issue I found in snippet.php: I had to change the
> setMaxLength validation for CONTENT to PHP_INT_MAX (it was hardcoded to a
> value out of range on 32-bit).

**Comment by jstanden** [comment]
This should be fixed in 8.1.3.

**Comment by ksuther** [comment]
This is still causing some problems on 32 bit systems. `strBitsToInt` with a value of '32 bits' returns results in overflow by 1. I was able to fix the problem locally by changing it to `DevblocksPlatform::strBitsToInt($n) - 1` in `setMin`, `setMax`, and `setMaxLength`.

**Comment by jstanden** [comment]
Reopened. We'll have to spin up a 32-bit VM and make sure it gets included in testing.

Thanks for letting us know!

**Comment by jstanden** [comment]
We'll probably require 64-bit PHP in Cerb 8.3.1+.  It's not easy to even spin up a recent OS in 32-bit on AWS or Linode.

@ksuther What OS/version is your server?  Where's it hosted?

**Comment by ksuther** [comment]
We just switched to 64-bit Debian last week, so this isn't a problem for us anymore. It was running Debian 9 at Linode (just provisioned a long time ago).

**Comment by jstanden** [comment]
Glad to hear it. :) Aside from validation, some of the new functionality like currency and decimal custom fields need the larger ints.
