### ISSUE TITLE
[API] Pagination fails when a quick search 'q' string is present

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#441]
It's been reported a couple times in the last two days that when using the API, paging the results works *until* you add a 'q' search string.  With that query string, regardless of the page requested, the API returns the first page of results.

**Comment by jstanden** [comment]
This is probably due to `addParamsWithQuery()` resetting the paging.  I'll reproduce it and get a fix into 8.1.3.

**Comment by jstanden** [comment]
Fixed in 8.1.3
