### ISSUE TITLE
Participant exclusion uses a substring match, even without wildcards

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#442]
Customer reported an odd behavior when replying to one particular ticket - it wouldn't include the sender, even though that address wasn't banned or excluded.   One of the excluded addresses, though, was a *substring* of the sender address on this ticket, and that was enough to keep it from being used (I verified by changing the excluded address (whereupon it worked) and changing it back (and it didn't)).

The excluded address was like "user@example.com", and the from address that was being wrongly excluded was like "someother.user@example.com".

**Comment by jstanden** [comment]
Fixed in 8.1.3
