### ISSUE TITLE
Task status subtotals don't add filters properly

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#443]
When viewing a Task worklist, subtotaled by Status, clicking any of the status types (open/closed/waiting) adds a filter of "Status is ", and the worklist is then empty (because of the faulty filter).  You can correctly add things like "status:closed" from the quick search, and that works, but the subtotal links are not working.

**Comment by jstanden** [comment]
I can reproduce this. Fixing for 8.1.3

**Comment by jstanden** [comment]
Fixed in 8.1.3
