### ISSUE TITLE
[Mail/Drafts] 4-byte emoji in a composed message breaks draft saving

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#449]

**Comment by jstanden** [comment]
This relies on #59 + #444

**Comment by jstanden** [comment]
This should now be fixed in 9.0.7.

**Comment by tullyhansen** [comment]
You're my hero! 😍  Now waiting on 9.0.7 to drop in Cerb Cloud…

**Comment by jstanden** [comment]
Hey @tullyhansen! I just applied the fix directly to your instance ahead of the update. See if that works properly now.

**Comment by tullyhansen** [comment]
It took an effort of will to reload the page with emojis in the middle of a draft (hard-won experience) but… yessssssssss! Thanks so much!

(Now for emoji in sticky notes… have I filed for that already? 😝)

**Comment by jstanden** [comment]
I'll check and file that if it isn't already. :)

**Comment by tullyhansen** [comment]
#59, I think? And #645 will hopefully get caught in the crossfire.

**Comment by jstanden** [comment]
For sure. At the moment, full `utf8mb4` support requires changing the charset/collation of the entire schema in MySQL. We'd need to set that on the MySQL connection to be able to save 4-byte content into any field.

The stopgap fix for drafts mirrors what we're doing with message content -- we just treat it as binary content and don't enforce any charset.

I'm all for using utf8mb4 as a default, but we also need to make sure people aren't using the MyISAM storage engine anymore, since it has a much lower key length limit when using text-based fields in compound keys (1000 bytes vs ~3000 for InnoDB).

That doesn't affect most of our schema, but it does come up. There are also field limits like `varchar(255)` which effectively store fewer characters than expected with 4-byte characters. That can affect ticket subjects, validation, and the like.

If we had started the project today, we wouldn't have even made the charset configurable, and we would have just used utf8mb4 everywhere. It's a shame MySQL's utf8 default has always been a misleading 3-bytes.

We're getting closer to being able to do that.
