### ISSUE TITLE
When removing customfield/set/similar, warn(prevent?) if used by bots/records.

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#466]
Recently had to remove a customfield set to test something and work around an issue. Doing so, I removed that data from some bots which meant they started misbehaving.

Without the ability to do a reverse check from the data set to the bot, this could be quite bad. Likewise, there is no way to see what data sets are in use by each bot without going through them one by one. (We have around 15 bots, with about 10 behaviours on each).

A warning on delete such as "this is being used by X bots, or has X tickets with data that references this set" would be nice but for bots especially, maybe a "bot healthcheck" could be designed that runs through each step and finds instances of variables selected but no possible valid outcome as attached.

![screen shot 2017-10-13 at 8 45 17 pm](https://user-images.githubusercontent.com/15971590/31563546-7627dea6-b057-11e7-85b7-d20b4c76b979.png)

**Comment by jstanden** [comment]
Our longer term goal here is to provide a feature for 'instanced' packages, where those resources could be owned/managed by the package. When the package updates, it would also update its underlying resources. Automations will make this easier in 10.0+ compared to bot behaviors now.

**Comment by jstanden** [comment]
At the very least, we should be warning about existing values being set on a custom field when deleting it too.

**Comment by jstanden** [comment]
This is possible in 10.0 now since custom fields are referenced by a URI rather than ID.

Automations also log errors automatically. The `on_error:` event can handle this gracefully.
