### ISSUE TITLE
Installer and servercheck.php both die ungracefully without mbstring

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#470]
Granted, it's a prerequisite, but we don't even get to the point of being able to say "hey, you need this thing, too"

**Comment by jstanden** [comment]
The installer has a check for mbstring at the top, but I fixed a call to an `mb_` function in `servercheck.php` which would have caused that issue.
  
It was added to `install/index.php` on 2017-03-15.  Was this an older version?
