### ISSUE TITLE
Add ability to move to a group without bucket (non-bulk)

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#472]
When moving a ticket to a group, you have to specify a bucket specifically.

It would be nice to be able to just specify the group which then defaults to the default bucket.

Would help with some logistical troubles in some bots when you have lots of groups/buckets.

**Comment by jstanden** [comment]
If you use the records API (Actions -> Record -> Update) you can just provide a `group_id`. I'll see about doing the same for the 'Move to' action.

**Comment by iammattmartin** [comment]
Ta - we actually did this some time ago and works well.... just didn't want to close this without reason!
