### ISSUE TITLE
API attachment upload with same name

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#476]
We've found a potential issue with uploading attachments via the API.

When we do this for an attachment that may already exist (i.e same name only), that is re-used meaning both tickets (original and new) then reference the same single file. The same behaviour does not occur via the web interface. i.e customer submits a file called image.png with some content and then another customer submits a different ticket also with image.png - the content ends up being the same.

Sizes of files does not seem to alter the behaviour and the only way around this is to fudge the file name on upload to ensure uniqueness but that is not ideal.

**Comment by jstanden** [comment]
I'll give this a test today.

**Comment by jstanden** [comment]
I'm not able to reproduce this through the API. The `storage_sha1hash` field is used to determine a match, with a second match against `name`.

It sounds like you're getting back a NULL SHA-1 hash, which ends up using just the file name to match. This behavior would be incorrect, and I can tweak the code to always fail a dupe check with a blank SHA-1 hash.

The real question is why you're getting a NULL hash back from the upload.

**Comment by iammattmartin** [comment]
Interesting. I will let D know.

I suspect this is why he raised #473. I could be wrong but I will update once I know more.

**Comment by jstanden** [comment]
How big is the file being uploaded? Does the attachment have valid content?  The API makes you base64 encode the content, so it's possible you're overflowing the max upload size in PHP or the web server. Or the encoding of the content fails a `base64_decode()` for some reason, and `sha1(null)` is giving you back a constant `da39a3ee5e6b4b0d3255bfef95601890afd80709`.

**Comment by iammattmartin** [comment]
Small files - less than a few hundred K.

WIll come back to you on the other question/checks.

**Comment by jstanden** [comment]
k! I'll push the fix for including `storage_sha1hash` in the API response, since it may assist with debugging. D can also check the `attachment` table in the database.

**Comment by iammattmartin** [comment]
@jstanden I believe this is now sorted (non-bug, sorry) with the added debug which helped massively.

**Comment by jstanden** [comment]
k! Glad to hear it. 👍
