### ISSUE TITLE
Setting and unsetting multiple checkbox type custom fields via the API

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#485]
When updating a resource via the API, I cannot determine any way of unsetting a custom field when it is of type: (X) Multiple Checkboxes.
If custom field 10 (custom_10) has options such as 'one', 'two', 'three', you can set each individual option custom_10 = 'one', but how do you remove the option? I also cannot determine a way of setting multiple values at one such as custom_10 = 'one','two'

**Comment by jstanden** [comment]
You can prefix the given values on multiple checkboxes with `+` (implied) or `-` to perform a combination of setting and unsetting values in a single request.

**Comment by mrlilly** [comment]
custom_10 = '+one' // adds one 
custom_10 = '-one' // removes one
Are you implying that you can do:
custom_10 = '-one + two'
As this just sets an option of 'one + two'

**Comment by jstanden** [comment]
Like this:

![api-multi-checkboxes](https://user-images.githubusercontent.com/63288/32115707-b200228a-bafc-11e7-9d35-1dd6ea3bfae9.png)

**Comment by iammattmartin** [comment]
I think we tried everything but. ;)

Thanks!

**Comment by jstanden** [comment]
Sure thing!  The `[]` syntax creates an array in PHP for that field name.  We'll make it more clear in the docs.
