### ISSUE TITLE
Options on custom fields should be enforced

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#486]
If you update a resource via the API and set a value on a custom field that has a pre-determined list of options ((X) Multiple Checkboxes, (D) Dropdown/Picklist), the value should only be saved if it matches one of the options.

If you have custom field (custom_10) on a ticket with options 'one', 'two', 'three' and set the custom field value for that ticket to 'bananas' - the value will be saved. Not only that, it will update the custom field options list to include 'bananas', then this value can be used on all tickets.

**Comment by jstanden** [comment]
That behavior exists for importing records with yet-unseen custom field values. It's a simple toggle in the method for setting custom field values to allow new values or not. We just need a way to expose that option to the API.

The default right now assumes that the enforcement of valid options happens in the requesting app.  The valid options for each custom field can be cached from: https://cerb.ai/docs/api/topics/custom-fields/#building-a-list-of-the-available-custom-fields
