### ISSUE TITLE
[Custom Fields/Links] Add multiple 'record links' as a single custom field type

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#489]
Right now you can add single 'record link' custom fields. It would be useful to be able to link multiple records using choosers from a single field.

For instance, if 'tag' was a custom record', a record could have multiple tags with a 'record links' custom field named 'Tags:'.

This would remove the burden from context links.

**Comment by iammattmartin** [comment]
This would be handy when linking to previous ticket(s!) too.

**Comment by jstanden** [comment]
Duplicated by #270

**Comment by jstanden** [comment]
Implemented in 9.4
