### ISSUE TITLE
[Cards] ESC close confirmation on all card editors

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#491]

**Comment by iammattmartin** [comment]
Would there be an option to disable this? I've noted that when doing lots of work on bots/cards, the esc confirmation actually becomes a bigger hindrance.

**Comment by jstanden** [comment]
If you close the popup from the (x) icon it ignores it.  We could add a modifier to ESC to bypass it as well (`Shift+ESC`, etc).

**Comment by iammattmartin** [comment]
Yeah.. it's more having got in to the habit of clicking off the window or just hitting esc. ;)

**Comment by jstanden** [comment]
Yeah, it could be annoying. But not as annoying as losing work from hitting ESC on the wrong popup. We'll figure something out. :)

**Comment by jstanden** [comment]
You can just hit ESC and ENTER to confirm the close warning too.

It's possible later on that we could only give a warning if the form was modified in some way.

**Comment by jstanden** [comment]
No other complaints in the past ~16 months. Closing this out.
