### ISSUE TITLE
Cannot set custom field values on messages via API

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#501]
As there is no end point for updating messages via the API, it is not possible to add/update custom fields for a message.
In an ideal world it would be great if we could send the message custom fields when creating and replying to a ticket and these would be applied to the message.

**Comment by jstanden** [comment]
I'll give this some attention.  As well, in the 8.2 release we have an abstract /records API that can work with any record type in Cerb (including custom records). It covers everything automatically using the per-record permissions from 8.1 and will avoid these kinds of oversights going forward.

**Comment by jstanden** [comment]
This can be done with the abstract records API now: https://cerb.ai/releases/8.2/#records-api

I'll look at implementing message custom fields on compose/reply API calls.

**Comment by jstanden** [comment]
Use the Records API: https://cerb.ai/docs/api/modules/records/
