### ISSUE TITLE
[Feature request] change title displayed on project boards

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#512]
It's not currently possible to have tickets on a project board and not have them show the mask in the title.  Customer requests the ability to modify (in the object template for the project board) the title that will display.

**Comment by jstanden** [comment]
This should be easy enough.  When configuring the project board and providing the default query and template for each record type, we could add a field for the title.  If blank we'd just default to `_label` like it's doing now.

**Comment by jstanden** [comment]
This is possible in 10.0+ since project board cards now use sheets to render their entire card. That gives full control of the label.
