### ISSUE TITLE
Records API for message context will not allow address_id to be set

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#522]
To create a record for a message using the new records endpoint, it will not allow address_id to be set and says it is required when you do not set (which is correct as a message would require a target recipient)
```
$postfields = [
    ['fields[ticket_id]', 9999],
    ['fields[address_id]', 111],
    ['fields[content]', 'Some content']
];
$out = $cerb->post($base_url . 'records/message/create.json', $postfields);
```
returns:

{"__status":"error","__version":"8.2.1","__build":2017110601,"__error":"ERROR_PARAM_INVALID","message":"'address_id' is not an editable field."}

**Comment by jstanden** [comment]
The `/records` API uses the dictionary keys rather than the database keys, so you'd want to use `fields[sender]` (for a full email address) or `fields[sender_id]` for an ID.
