### ISSUE TITLE
[API/Records/Sensors] Allow sensor params to be set from the Records API

### ISSUE THREAD

**Issue by johnryanlee** [jstanden/cerb#534]
I am trying to create Sensors in Cerb 7.3.11 but cannot create a port based sensor because the fields in question are not available.  The db shows a column for `params_json` but the API does not allow me to set this field.

                        $sensor_created_postfields = array(
                                array('name',$sensor_name),
                                array('type', `cerberusweb.datacenter.sensor.port`),
                                array('params_json','{"host":'.$sensor_name.',"port":"8291"'),
                                array('status', 'O'),
                        );

My alternative is to import the data from CSV but then I have column matching issues as well as delimiter problems because of the params_json being a JSON format.

**Comment by jstanden** [comment]
We can expand the records API in 8.2 to support params as JSON, since several other records do the same thing already. That's not something we can easily backport to 7.3 though, since it depends on the recent 8.x abstraction (records API, validation, roles). https://cerb.ai/docs/api/modules/records/

**Comment by johnryanlee** [comment]
Thanks for the feedback.

I understood it may not be an option but wanted to make sure I wasn't missing something.

**Comment by jstanden** [comment]
This plugin was phased out in 10.0, but its functionality can be wholly reproduced with custom records and automations.
