### ISSUE TITLE
Bot responses and response timing

### ISSUE THREAD

**Issue by johnryanlee** [jstanden/cerb#535]
We have implemented an automated email for certain situations which reads custom fields and compiles the email to the customer upon ticket closure.  The issue here is that bot responses appear to not be taken into consideration though so if a worker logged a request, didn't respond, and closed the ticket.  The client would get their feedback through the bot but the communication wouldn't count.

- Is it possible to make the email come from the ticket owner?
- Is it possible for any response to be counted towards response times?

**Comment by jstanden** [comment]
Are you using the `Send email to recipients' or 'Send email' action?

What kind of stats are you running in the close event?  Are you loading the ticket's messages into a behavior list variable?  If so, you should have full control over which messages are included.

With 8.2+, you'd be able to use the Records API to change the `worker_id` on an outgoing message if you want bot replies to count as the owner.
