### ISSUE TITLE
Mail transports - Maximum Deliveries Per SMTP Connection

### ISSUE THREAD

**Issue by johnryanlee** [jstanden/cerb#536]
At what frequency are mails sent?
If we wanted to email 40000 contacts from Cerb, would the emails be delivered in batches of 20 per cron run?

**Comment by jstanden** [comment]
The mail queue scheduler job will attempt to deliver as many messages as it can within 30 seconds (using pages of 25). You can schedule that to run as often as you like (as fast as per-minute with cronjob, and within seconds using Cronfire).

The time to deliver a 40,000 message broadcast depends on your mail transport (generally SMTP). The default 'messages per connection' of 20 isn't the limit per scheduler run, it's just how many messages are sent before we disconnect and reconnect to SMTP in the same request.  If you know your SMTP can accept more messages per connection then you can raise that on the mail transport.

Most SMTP servers will quickly accept mail and then queue it up for delivery in the background. If you have expensive rules for each accepted message (header checks, etc) then it could take longer.

For reference, in Cerb Cloud we often send out ~1,000 messages in 1-2 runs of the scheduler.  With Cronfire those are 1 minute apart.

We've been experimenting with allowing other queue engines in Cerb (like Redis), which would allow those background scheduler jobs to be highly parallelized when necessary.
