### ISSUE TITLE
Is show_meta now off by default for API requests

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#541]
Running 8.2.4 the meta data / show_meta option in API requests now appears to be off by default, where as is used to be on by default?

**Comment by mrlilly** [comment]
Found the change in
https://cerb.ai/releases/8.2.3/

You need to update your documentation: https://cerb.ai/docs/api/topics/responses/

**Comment by jstanden** [comment]
Will do! Thanks :)
