### ISSUE TITLE
Adding an attachment to a message when creating with records API

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#542]
When a message is created via the records API, what is the key to add an attachment to it using the attachment ID.

**Comment by jstanden** [comment]
When creating or updating the attachment, use:

~~~
fields[attach][] = ticket:123
fields[attach][] = message:123
...
~~~

**Comment by mrlilly** [comment]
So are you saying this cannot be done from the create message call?
On the depreciated tickets API module, you only need to add the file_id[] to the payload when creating a ticket or replying.
The above is fine if you are creating the attachment after the message. Seems a backward step if I have to make two calls to the API if I already have the attachment ID.
Sorry for replying to an old closed issue.
