### ISSUE TITLE
Improve log text on SC actions

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#55]
When an action is logged from a customer portal, we should indicate that said action was done through the portal.  (This might carry over into also logging things as sourced from the Web-API, or from relay functionality (I'd personally like it if relays had a clear indication in the log that it was proxied from a relay instead of the main UI).)

Source is a confusion that arose over a customer closing a ticket from the SC, and the log entry just said "changed ticket to status closed" (since the contact had no name).

**Comment by jstanden** [comment]
This hasn't come up again. It won't be necessary with the portal builder in 10.1+
