### ISSUE TITLE
Different behaviour for HTML template on new and reply messages

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#552]
On new messages when you opt for a HTML message mode, using - default - as the template, the text is always sent/formatted as the cerb default.

When you reply, also using the - default - as the template, it is sent using the group/address template.

This behaviour is inconsistent and should work the same regardless if the message is new or a reply.

**Comment by jstanden** [comment]
This needs to be verified in the current code. It's been heavily tested since the new compose/reply toolbars/editors, and shouldn't still be an issue.

**Comment by iammattmartin** [comment]
Confirmed and appears to now be consistent.
