### ISSUE TITLE
Add ability to strip out original_message on send (and receive?) or remove via bot

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#553]
There isn't a way to neatly remove the original_message.html attachment from sent messages, either via a bot (after sent from a worker) or a scheduled task.

A code edit could do this (https://twitter.com/cerb_ai/status/937879475680821248) but isn't elegant and seems to fall outside of what cerb tries to do (everything usable via bots).

I would be nice to be able to remove these attachments on sent messages but maybe also have the ability to add on other bot types, i.e new message added to ticket etc.

Similar to how you can remove attachments due to size, file name matching could be a good addition.

**Comment by jstanden** [comment]
This can be done with the `attach` field on attachment records since 9.3.2. You can prefix those `type:id` tuples with `-` to unattach.

e.g. `fields[attach][] = -ticket:1234`
