### ISSUE TITLE
"Send email to recipients" breaks previous emails

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#554]
In a later release, a template selector has been added to "Send email to recipients" on bots.

This causes quite a problem when you have multiple brands each with their own outbound template. Before, using - default- worked perfectly as it inherited the template from the group so the right template was always used.

Now it does not because it wants a hard-set value so we'd have to then build many decisions and actions just to replicate the same email for each brand/template - this is a massive task.

Can the old functionality be restored, or if no template is selected, it uses the default for the group as it used to?

**Comment by jstanden** [comment]
See: https://github.com/jstanden/cerb/issues/507#issuecomment-343317514

**Comment by iammattmartin** [comment]
Thanks - are you able to give a working example as I cannot see anyway to implement, although its 7am so could be a case of fussy head.
