### ISSUE TITLE
[Feature Request] Add an event point to card popups

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#559]
Adding an event point to card popups should allow user-contributed JS to reflow / reformat the layout of those cards.

The specific end goal of the initial request is to move the "Comment" block above the custom fields on a ticket card, but a generic solution would be better (so long as it allows the specific use-case).

**Comment by jstanden** [comment]
This is related to the '[UI] Record editor opened' event added in 9.2, but it would be on cards instead.

**Comment by jstanden** [comment]
This is no longer required since we implemented card widgets.
