### ISSUE TITLE
Indicate lack of name in log entries

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#56]
Source complaint is a confusion about a log entry that stated "changed ticket to status closed" with no clear actor.  The context_activity_log made clear that it was a contact object that had done the action, but said object had no name associated with it.  We should indicate that lack of name in something like "Un-named Contact changed ticket to status closed" (with a link to the object profile on "Un-named Contact").

**Comment by jstanden** [comment]
This hasn't come up in years. Closing.
