### ISSUE TITLE
Tweets broken on upgrade (fixed by re-saving account link)

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#566]
Since (we think), 8.2.7, we were not getting any tweets.

We had to go in to settings and twitter accounts and just re-save each connected account.

Is that an issue as I wouldn't have expected an upgrade to cause that needing to be done.

**Comment by jstanden** [comment]
It shouldn't have happened on an upgrade unless your encryption key (for the connected account params) changed somehow.

I haven't had any other reports on this yet; but I'll see if we can reproduce it.

**Comment by iammattmartin** [comment]
I'm not aware of any change (bar the git commands to upgrade etc). Process followed as normal and have not seen this happen before.

**Comment by iammattmartin** [comment]
@jstanden I've not seen this happens since over the last few upgrades. I suspect it was just a one-off so may be a non-issue.

**Comment by jstanden** [comment]
Thanks for keeping an eye on it. :)
