### ISSUE TITLE
reverting a custom template dies

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#567]
When you revert a custom template in 8.2.5, it greys out the list behind the popup (and successfully deletes / reverts that template), but it never refreshes to close the popup and rebuild the list.

**Comment by jstanden** [comment]
I'll check in 8.2.8

**Comment by jstanden** [comment]
@Hildy No issue in my local install. Was this in Cerb Cloud or on a client server?

**Comment by Hildy** [comment]
@Jeff Current Cerb Cloud site (not ours)

**Comment by jstanden** [comment]
Looks like this is an instance-specific issue.  It's worth considering for future scaling, but presently isn't a bug.
