### ISSUE TITLE
Add long tweet support.

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#568]
Since twitter increased the length, we're getting tweets in with a link to the rest of the content instead of the text itself (which just doubles the work that has to be done).

Also, when replying, it should count down to the new character limit instead of the old one (although does not prevent longer messages - more just visual).

**Comment by jstanden** [comment]
Hi Matt!  I'll fix this.

**Comment by jstanden** [comment]
Hi Matt! This was actually implemented by a contributor: https://github.com/cerb-plugins/wgm.twitter/pull/6

I merged it into the Plugin Library.
