### ISSUE TITLE
[Support Center] Allow required filters to be added to worklists in the Support Center

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#572]
Currently you can only default the editable filters in the Support Center worklists. We've had requests to modify the required filters as well. This could use placeholders and would be simple to do with quick search.

**Comment by salkurdi** [comment]
Thanks Jstanden, another way around maybe is to archive cases is there anyway to do so.

**Comment by jstanden** [comment]
This is supported in the portal builder in 10.0+
