### ISSUE TITLE
Viewing a KB article on the public portal 'update's it internally

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#574]
Testing something completely unrelated, I went to our KB and clicked on an article labeled as updated 21 days ago.  I then searched for it in the admin UI, and it was marked as updated "1 minute ago".  I think updating the view_count is flagging the whole record as updated, and it shouldn't.

**Comment by jstanden** [comment]
At the moment, any record change updates the timestamp. But we do have an option to ignore it for certain writes like this.  I can take a look.

**Comment by jstanden** [comment]
Implemented in 8.2.9
