### ISSUE TITLE
[Improvement] Deep search on watchers

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#591]
Watchers can't currently do a deep search, but it would be a bonus if it could.

**Comment by jstanden** [comment]
This came up today in a worklist where a worklist would show open tickets watched by workers who had an 'away' custom field set.

**Comment by jstanden** [comment]
This is something I have in my dev environment but need to move into 10.x.

**Comment by jstanden** [comment]
Implemented in 10.1
