### ISSUE TITLE
Connected Accounts popup focuses the close button, but the focus window is offset

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#6]
![image](https://cloud.githubusercontent.com/assets/64052/22717812/0966c084-ed52-11e6-8e09-e5427ec8690e.png)

When first loaded, the connected accounts popup has a weird little focus window around the close button, but offset lower.  This shows in Chrome, but not Safari.  

(This is a seriously minor issue.  ;) )

**Comment by nbeernink** [comment]
I always get that too and thought I reported it. But I guess not! :) Can confirm this happens. :+1:

**Comment by jstanden** [comment]
It looks better in Safari:
![screen shot 2017-02-16 at 2 18 38 pm](https://cloud.githubusercontent.com/assets/63288/23043897/dc672616-f452-11e6-8179-01ec66ad72c2.png)

The main fix here should be focusing one of the buttons on the popup for keyboard navigation.

**Comment by jstanden** [comment]
This happens because the popup doesn't have any form elements. The bubbles are just `DIV`s. Some browsers like Safari also don't `<TAB>` through links by default.

This isn't really a bug, although that popup could be reorganized later to address the lack of keyboard shortcuts.
