### ISSUE TITLE
[Explore Mode] Next/previous shortcuts not working with French keyboard layout

### ISSUE THREAD

**Issue by tullyhansen** [jstanden/cerb#617]
Hi, longtime user, first time issue filer ❤️… `]` and `[` work wonders on standard Australian Mac keyboard layout, but my French-PC-toting-friend has no such luck. I gather the issue is something like [this one from `jupyter/notebook` project](https://github.com/jupyter/notebook/issues/2379) where square brackets are assigned to some modifier key monstrosity… the `event.which` values for Explore mode seem to be hard-coded (at https://github.com/jstanden/cerb/blob/8.3/features/cerberusweb.core/templates/explorer/index.tpl) and (forgive my nonexistent JS literacy) are maybe rejecting anything with a modifier key? Ideal solution seems to be either make square brackets work or offer an alternative for non-English keyboard layouts.

![French keyboard layout](http://www-01.ibm.com/software/globalization/topics/keyboards/images/fig2.gif)

(Thanks!)

**Comment by jstanden** [comment]
Hi @tullyhansen!  I'll find a way to make this work for your friend.

Specific to the explore mode, I'm sure we could tolerate modifiers on the `[` and `]` keys.  However, it looks like they're inconveniently positioned, and it would probably make more sense to make the keys configurable.  In that layout, the `>` and `<` key looks like a good candidate (if `<SHIFT>` was allowed).

**Comment by tullyhansen** [comment]
Wow, thanks for the rapid response! Took this back to my friend/colleague who suggested `;`/`:` could make a good pair (as a bonus, these double as the `<`/`>` keys on QWERTY layout, which makes some conceptual sense). I (we) trust in whatever you come up with, though! Thanks again.

**Comment by jstanden** [comment]
This should be addressed in the 8.3.3 update.  Workers will be able to customize the keyboard shortcuts for explore mode, including any modifiers (shift/cmd/etc).

**Comment by tullyhansen** [comment]
Brilliant! Thanks for your help and patience @jstanden, feel free to close.

**Comment by jstanden** [comment]
This is completely done in the code, it just needs a worker settings page to configure. The shortcuts would set the variables here: https://github.com/jstanden/cerb/blob/9.0-beta/features/cerberusweb.core/templates/explorer/index.tpl#L89

With jQuery Hotkeys we can also define human-readable shortcuts like `Shift+A`.
