### ISSUE TITLE
Download dropdown doesn't work on Windows

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#619]
Windows 10, Cerb 8.3.0.

In Chrome, Brave, Edge, Firefox, Opera, and Safari the attachment dropdown "Download" option does nothing.  Download from the attachment card popup does work (only tested on Chrome).

**Comment by jstanden** [comment]
@Hildy This seems to work in BrowserStack w/ Win10 + Cerb 8.3.1 + Edge 14-16.  I'm prompted for a place to save the file, and can confirm it's readable after saving.

**Comment by jstanden** [comment]
I believe this was fixed a while ago. Reopen if not.
