### ISSUE TITLE
Site - Plugins Page

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#624]
Plugins page is broken.

https://cerb.ai/resources/plugins/

Linked from: https://cerb.ai/docs/plugins/

**Comment by jstanden** [comment]
Thanks, Matt!  We have a new section under development for documenting every plugin. It looks like that link was published prematurely.

**Comment by jstanden** [comment]
Fixed on the site.  We'll bring the link back as soon as the new plugins section is published.
