### ISSUE TITLE
Cursor jumping to subject line while composing reply seemingly at random

### ISSUE THREAD

**Issue by tullyhansen** [jstanden/cerb#632]
Not sure whether there's a better channel for this sort of thing, but I and one other colleague have noticed that on occasion while in the middle of writing a reply, focus jumps to the subject line mid-sentence. I'd written it off as trackpad brushing/mis-clicking, but the fact that it's corroborated by someone else and I've seen it happen in cases where cursor is nowhere near subject field makes me suspect something else… perhaps there's a hot key/shortcut to jump to subject line that I'm not aware of and am inadvertently triggering?

It's not showstopping, but frequent enough to notice – say up to half-a-dozen times in a regular 8-hour workday?

In my case, this is in Safari 11.0.3 a MacBook Pro on macOS 10.13.13. I don't recall seeing the behaviour before Cerb 8.3 (but as mentioned I may well have done and just have written it off). Let me know if there's any more info I can provide to assist! Thanks.

**Comment by jstanden** [comment]
Hi Tully!

Feel free to ask any questions of report any issues here.  Even if you write to team@cerb.ai, chances are we'd track dev issues here anyway. :)

This is the first I've heard of the cursor jumping back to the subject line on replies.  There are a lot of shortcuts in that textarea, but they all begin with `<SHIFT>`+`<CTRL>`, and none involve the subject line.  I believe with Safari, you can't even `<SHIFT>`+`<TAB>` backwards to the subject line from the message body.

I use Cerb 8.3 w/ Safari 11.0.3 and macOS 10.13.3 on a 2017 iMac Retina 5K.

I did have one other report from an iPad user that `<SHIFT>` + `<LEFT/RIGHT ARROW>` on their Bluetooth keyboard scrolled the page while they were writing a reply.

You could temporarily disable keyboard shortcuts (from your Profile->Settings).  That would rule those out.

If you're up for it, you could try using a different browser for a couple hours to see if it happens.  It wouldn't be the first time we ran into a funky WebKit edge case.  This was one of my least favorite: https://bugs.webkit.org/show_bug.cgi?id=176896

Those would help narrow it down.

**Comment by tullyhansen** [comment]
Hey Jeff,

Thanks for making a newbie feel so welcome… as for this issue, I'm yet to try in another browser (old habits…) but should I figure out any repeatable steps for Safari I'll let you know.

**Comment by tullyhansen** [comment]
It's _almost certainly_ triggered by spacebar (or space followed by a certain letter?), and _almost always_ when I'm typing at a fair clip (for a hunt'n'pecker), so I'm usually a few characters past where the action's happened by the time I notice. Nothing further to report at present!

**Comment by jstanden** [comment]
Any chance this is related to the issue with hardware keyboard cursor navigation on replies when using explore mode?

**Comment by tullyhansen** [comment]
Sorry Jeff, not too sure… but on the plus side, I don't recall having this issue in recent… weeks? Months? I _have_ switched to Safari Technology Preview sometime in the interim (love me some tab favicons!), so whether it's that, some change in habits, or just good luck I'm not sure… I've also not seen anyone else on our team complaining. If you can't reproduce, feel free to close, I'd say?

**Comment by jstanden** [comment]
Great. Thanks for the update! I assume it's a similar issue to the arrow keys on explore mode (which was reported to the WebKit team). We can close this and reopen if it reoccurs. :)
