### ISSUE TITLE
Records API, creating message with html_attachment_id

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#633]
If you are using the records API to create a message, how do you create one as if it was markdown.

With the original tickets API you could set content_format = markdown and the markdown would be parsed and the html_attachment would be created?

**Comment by jstanden** [comment]
You can still use the compose and reply endpoints to write messages in Markdown: https://cerb.ai/docs/api/modules/tickets/

You can use the parser for raw inbound email: https://cerb.ai/docs/api/modules/parser/

If you really want to create a message with the records API, see: https://github.com/cerb/cerb-release/blob/master/install/packages/install_tutorial_package.json#L1736 (that record and the two above it)
