### ISSUE TITLE
{{current_worker_id}} not working when calling saved searches via API

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#637]
We're using {{current_worker_id}} in saved search via the API but it looks like the worker isn't substituted for the cerb user based on the bearer token.

This means when a worker pulls the saved search results via the API, it does not return relevant data.

Most basic example we used was:

```owner.id:{{current_worker_id}}```

Should return tickets owned by that user and only those. Adding worker to the ticket as owner, does not reveal anything.

Works via the GUI.

**Comment by jstanden** [comment]
I'll give this a test.

**Comment by jstanden** [comment]
Fixed in 8.3.3
[cerb-637.patch.txt](https://github.com/jstanden/cerb/files/1842702/cerb-637.patch.txt)
