### ISSUE TITLE
Merging tickets doesn't seem to update value for 'Updated' as expected

### ISSUE THREAD

**Issue by tullyhansen** [jstanden/cerb#638]
# Steps to produce

1. Merge recent ticket `XYZ` (received 1 hour ago, say) into existing older ticket `ABC` (updated 24 hours ago, say)

# Expected behavior

Ticket `XYZ` is merged into `ABC`, `ABC` subsequently shows `Updated` value of `1 hour ago`

# Actual behavior

Ticket `XYZ` is merged into `ABC`, `ABC` subsequently shows `Updated` value of `24 hours ago`

# Additional information

Maybe I'm just misunderstanding the thinking here, but this has tripped me up a couple times, as I have tabs with Ticket Worklists sorted on `Updated` value (to catch oldest tickets) – I'm seeing tickets that look to have gone days or weeks without updates, only to find they've resurfaced because of a merge that isn't reflected in the `Updated` value. Hope that makes sense!

**Comment by nbeernink** [comment]
We worked around this by adding a "last incoming" custom date field to a ticket and update that each time a new ticket is popped. Then you can filter by that status to see the oldest tickets.

```json
{
  "behavior":{
    "title":"Last Incoming timestamper",
    "is_disabled":false,
    "is_private":false,
    "event":{
      "key":"event.mail.received",
      "label":"Message added to a conversation"
    },
    "nodes":[
      {
        "type":"switch",
        "title":"Message is incoming?",
        "nodes":[
          {
            "type":"outcome",
            "title":"Yes",
            "params":{
              "groups":[
                {
                  "any":0,
                  "conditions":[
                    {
                      "condition":"is_outgoing",
                      "bool":"0"
                    }
                  ]
                }
              ]
            },
            "nodes":[
              {
                "type":"action",
                "title":"Set last incoming to now",
                "params":{
                  "actions":[
                    {
                      "action":"set_cf_ticket_custom_46",
                      "mode":"",
                      "value":"now",
                      "calendar_reldate":"",
                      "calendar_id":""
                    }
                  ]
                }
              }
            ]
          },
          {
            "type":"outcome",
            "title":"No",
            "params":{
              "groups":[
                {
                  "any":0,
                  "conditions":[
                    {
                      "condition":"is_outgoing",
                      "bool":"1"
                    }
                  ]
                }
              ]
            },
            "nodes":[
              {
                "type":"action",
                "title":"Clear last incoming",
                "params":{
                  "actions":[
                    {
                      "action":"set_cf_ticket_custom_46",
                      "mode":"",
                      "value":"",
                      "calendar_reldate":"",
                      "calendar_id":""
                    }
                  ]
                }
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by tullyhansen** [comment]
Whoa, thanks @nbeernink! I'll poke around, but this sounds an even better solution. Was this new in 8.3? I musta missed it. Feel free to close – thanks!

EDIT: Wait, you're saying you do this on top of core Cerb functionality, is that right? It's not built-in? (Still new at poking and prodding Cerb – just trying to get my head around the fix here!)

**Comment by nbeernink** [comment]
Unfortunately we're still on 7.2.5. But you should be able to just add a custom field to tickets and import what I shared above. You just need to edit the custom field to update the proper field for you and then you can just set any ticket worklist to include that date column.

**Comment by jstanden** [comment]
As a quick stopgap, we added `Updated` as one of the fields considered by ticket merges (8.3.3); so you can just pick the most recent date.

This is a side effect of the recent abstraction bringing merge to all records. All of the values currently default to the oldest record as the target until you set them.  I can expand the interface for record merging so certain fields could provide defaults in a different order.

Contextually, the 'updated' field should select the most recent date first, and 'created' makes sense as the oldest date.

Another option would be just setting 'updated' to the current timestamp after any merge. That requires a quick tweak to the abstract merging interface so each record type could do that on their own terms. The 'updated' fields are almost standardized, but aren't completely yet.  When they are I can just clean that up and do it abstractly too.
