### ISSUE TITLE
Add API call to pull all saved searches and matching counts

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#639]
We use saved searches as filters, which gives a far more powerful way to deal with tickets - it works well (really well).

![screen shot 2018-03-21 at 11 27 29 pm](https://user-images.githubusercontent.com/15971590/37742890-6fde9eba-2d5f-11e8-90b1-25f888d60e2d.png)

We do have to pull each saved search for each worker user via the API (as the results can differ based on the worker and their groups) to get the total of matching messages.

It is fast but when each user has to check/call around 30 searches, and we do this every 5/10 seconds, X by the number of users - it's a lot of queries but does make the desk "live" so you can see things in near real time.

Could there be scope to be able to return all saved searches with their matching ticket counts? This would be far far far faster and suspect useful to a number of people.

**Comment by jstanden** [comment]
We just need API automations and all these variations would be handled cleanly.
