### ISSUE TITLE
Certain emoji characters not shown in titles of Workspace Widgets

### ISSUE THREAD

**Issue by tullyhansen** [jstanden/cerb#645]
Can use 1️⃣ but not 👁 in the title of a Workspace Widget – the latter renders like this:

![](http://com-agilebits-users.s3.amazonaws.com/tully/2018-03-27_03-51-58.png)

**Comment by tullyhansen** [comment]
Wait, this'd be because they're Unicode under the hood _presenting_ as emoji, never mind… but I'm looking forward to (hopefully forthcoming!) full emoji support! 🎉 

> Unicode Version 3.0
> The following characters we added to Unicode in 1999 and given emoji presentation status in the years 2010-2015… see https://emojipedia.org/unicode-3.0/

**Comment by jstanden** [comment]
You should be able to use 'utf8mb4' encoding on those tables/columns in MySQL.
