### ISSUE TITLE
Searches on tickets with contacts and custom fields

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#675]
We're seeing a consistent potential bug with search, or contacts and custom fields.

We have a custom field (drop down) on contacts for class (standard or VIP).

We want to have a search for open tickets and those that belong to VIP contacts below but this returns more than expected including contacts that don't have any value for the custom field set.

`status:open AND contact:(class:"VIP")`

So we tested just with `contact:(class:"VIP")` but this returned more contacts tickets than expected too. 

But when using `contact:(class:"VIP") AND contact:(class:"VIP")` it only returns the one contacts tickets we've currently set with VIP (expected behaviour). Even adding a status:open to that reverts to the original behaviour.

`class:"VIP"` on just contact searching works as expected.

I've double and triple checked but can't see any flaw in what outcome is expected so it looks like a bug some where.

**Comment by iammattmartin** [comment]
Could we give this one a nudge? I'm sure it's an easy fix.

**Comment by jstanden** [comment]
@Joefatawesome Can you reproduce this?

**Comment by iammattmartin** [comment]
Oddly, we've moved v9 to live since my post and this does not seem to happen anymore. On our v8 install that is offline, it does.

Will do more testing before we conclude all is well though.

**Comment by jstanden** [comment]
@iammattmartin Thanks! If it happens again, @ me here and I'll reopen.
