### ISSUE TITLE
Add 'Owner' as a sub-total-able column for Tasks

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#678]
Tasks can build subtotals for a number of fields, including all the custom fields, but oddly cannot subtotal by Owner.

**Comment by consolibyte** [comment]
Use-case:

I want to build a SUBTOTAL dashboard widget, which shows the # of incomplete TASKS per WORKER/OWNER.

Thanks!

**Comment by jstanden** [comment]
Implemented in 8.3.9
