### ISSUE TITLE
[Comments/Mentions] Allow @mention for entire groups on comments

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#68]
Migrated from JIRA: https://wgmdev.atlassian.net/browse/CHD-4470

**Comment by jstanden** [comment]
It would also be interesting if you could add dynamic `@mentions` powered by a quick search, so `@available` or `@coders` could work too.  Cerb would just run the search and notify the workers who matched it.  That could also cover group memberships -- and `@support-managers` -- but it wouldn't be limited to that.

**Comment by Hildy** [comment]
@jstanden - what about like '@group:(Sales)' as a grammar for that?

**Comment by jstanden** [comment]
@Hildy I think that would be super useful. We could use a worker worklist chooser for it, like deep search, which would help build the query.  It'd be nice to not require another record for managing the mentions (and the dynamic queries wouldn't have to worry about conflicting with existing mention names).

The main downside I can think of would be the lack of expressiveness.  Something like `@all` or `@available` or `@php-coders` is obvious to everyone in the log/notifications.  We could improve that by adding saved queries to quick search like presets. Then we could possibly allow a label for the query that gets replaced in the actual comment.  That'd be tedious for something that is used dozens of times per day, though.

Ultimately we want something like `@available-support` to map to `group:support isAvailable:"now to +15 mins"`. Maybe we just start with saved queries on quick search, and then we could allow some presets to have an optional alias which functions like an at-mention name.  That could be used in quick search itself to load a preset, in a chooser, or in this at-mention functionality.

Then we aren't left with a record just for `@mention` aliases on comments.  It's something more reusable as saved queries.

**Comment by Hildy** [comment]
We've got aliases for things in the conversational bots, so I like the idea of aliasing saved queries/filters.  This could potentially be more useful than just @Mention searches.

**Comment by jstanden** [comment]
Implemented in 7.4
