### ISSUE TITLE
Make CFs available to the "before sending worker message" behavior in Compose

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#680]
Not sure if this is even doable, because the ticket object doesn't exist yet, but a customer would like to use the custom field that was set by the worker on Compose (specifically, a language field) to change the signature.

**Comment by iammattmartin** [comment]
We have a similar need for this.

We set CFs on a new ticket which populate a prepend/append bit of text. Yet on a new message they don't work. They do work on each reply.

**Comment by beatbesmer** [comment]
Is there any workaround to pass custom- data (from a predefined dropdown / checkbox etc.) to the ticket, before the message is sent?

**Comment by jstanden** [comment]
Implemented in 9.3.2. The custom fields from the compose/reply form are now available as 'Sent message' placeholders in conditions and actions.

**Comment by beatbesmer** [comment]
If you’re happy and you know it, clap your hands! 👏🏻👏🏻👏🏻
This feature reduced a lot of "rework" and simplifies the workflow  👍. Many bot behavior profits of it.
