### ISSUE TITLE
[API] Return the limit with a collection of retsults

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#682]
The following totals are returned from the API when making a request for a collection of resources:
total (total amount of resources for the query)
count (amount of resources returned with this request)
page (the page of results requested)

The limit needs returning also, as the last page cannot be determined without it. For most pages the limit is the same as the count, but on the last page it could be different as it is the remainder of results and may not be the limit requested.

**Comment by jstanden** [comment]
Sure! It's assumed you're sending an explicit `limit` to the search, but it should be simple to include that in the results as well.  I'd really prefer to just move toward cursors where you get a token for the next page and don't need to bother with anything else.

**Comment by jstanden** [comment]
Implemented in 8.3.9
