### ISSUE TITLE
config controller doesn't remember where you were

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#684]
Click Setup -> Mail -> Incoming Mail -> Import, then click back to a normal page, then click Setup.

You'll see a blank page with nothing, when I would expect to be taken back to the setup page I was on most recently.

**Comment by jstanden** [comment]
Coincidentally, I had just imported a message for testing the last issue I looked at, so this was perhaps the simplest thing to ever reproduce. ;)

I see the same issue.  It just means we're not setting the right setup page ID into the session. It should be a quick fix for 8.3.9.

**Comment by jstanden** [comment]
Fixed. The issue was the 'Import' tab overriding the setup page ID for 'mail_incoming'. I removed that and we're all good.
