### ISSUE TITLE
Content can over-run the Peek dialog

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#690]
The specific example is a ticket peek that opens up and paging through to a message with really long HTML lines, the message area overlaps the sides of the peek.  See linked ticket for example.

**Comment by jstanden** [comment]
At the moment this is quasi-intentional, due to the `overflow` attribute on the popup (allowing popup menus to overflow the bounds of the popup). That prevents a width constraint on the email content. I'll play around with the CSS and see about handling both.

**Comment by jstanden** [comment]
Fixed in 9.0, and we can backport to 8.3.10 if needed.
