### ISSUE TITLE
Support @2x images for logos

### ISSUE THREAD

**Issue by Penderworth** [jstanden/cerb#692]
We just updated our branding, and we can't get the 1Password logo to look very nice in Cerb:

<img width="224" alt="screen shot 2018-06-30 at 9 33 36 am" src="https://user-images.githubusercontent.com/6487393/42127176-b8e4f202-7c48-11e8-9140-9aee3bbc1166.png">

It'd be great to support @2x images for logos.

**Comment by jstanden** [comment]
Sure, we could store a second higher-res logo image/URL and swap them with CSS media queries.  I'll give this a test.

**Comment by jstanden** [comment]
Implemented in 9.0 (for possible backport to 8.3.10)
