### ISSUE TITLE
Owner autocomplete in ticket edit peek shows worker ID instead of name

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#7]
On profiles/ticket/XYZ-12345-678, click the Edit button and then try typing in the name of a worker in the owner autocomplete.  It shows up with the ID instead of the name. 
![image](https://cloud.githubusercontent.com/assets/64052/22750637/6feb9232-ede6-11e6-9177-53d2c0acbf43.png)

**Comment by jstanden** [comment]
Fixed in 7.3.1
