### ISSUE TITLE
Add a "Timer" option

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#702]
We've got a potential use for a timer on a ticket that we can start on certain bot actions and then pause/stop on another bot action.

One of businesses is in a regulated market and we will soon have to measure the time it takes us to deal with a ticket from the point raised until resolved but this time should not count when with the customer.

I was thinking a custom field of sorts that has a trigger to start and stop. Counts up from 0 and converts that in to a time but this has to be within the internals of Cerb as it cannot rely on browser plugins to manually trigger this as it needs to happen on existing activity, i.e reply from user, start the timer; reply from staff, stop the timer.

Do-able?

**Comment by jstanden** [comment]
In 10.0 we're working on "automations", which are state machines. Their design allows them to run a few steps and then 'yield' (wait) for some trigger (e.g. time delay, user input, webhook/API, etc). That trigger could flip state when messages sent and received. At each point it could add seconds to an elapsed time field.

In the meantime, a form interaction widget on tickets could allow you to start/stop the timer (if enabled), and a sheet or record fields widget could display the state of the timer and the current times. All of that could be stored in a custom fieldset owned by a bot.

You could use custom records for this to keep an itemized log. Then a custom field on the ticket (or whatever record) is just the sum of those time records.

(Not winning any punctuality awards on this one)

**Comment by iammattmartin** [comment]
10 sounds good.

Would be good to have potentially a workable example on the latter. :)

**Comment by jstanden** [comment]
Sure! I'm finishing up a few things, then I'll mock this up and share the example. :)

**Comment by jstanden** [comment]
Automation timers are a new record type in 10.0. They can be enabled/disabled through events and linked to any number of records.
