### ISSUE TITLE
[Choosers] Persist worker changes to chooser worklist columns/properties

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#705]

**Comment by consolibyte** [comment]
👍  Following so I know when this is fixed.

**Comment by waa** [comment]
Followed...

**Comment by jstanden** [comment]
This shouldn't be as much of an issue in 10.0 since these things can move into interactions where you have full control over the sheet. As well, toolbars can be used in 'Record Fields' widgets rather than search buttons.

After upgrading, let me know if it continues to be a problem.

**Comment by beatbesmer** [comment]
Indeed, we can implement many things with sheets and interactions. This really added a huge value to CERB  👍 
How you'd recommend to profit of this e.g. for the worklists used by the global search?
