### ISSUE TITLE
[Mail/Tickets/UX] On ticket profiles, provide a visual indication when there are multiple client replies in a row since the latest worker reply

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#712]
Right now, the earlier client replies are all collapsed.

We should:

* Expand all client messages received since the latest worker message.

* Display the count of unread messages at the top of the conversation.

**Comment by jstanden** [comment]
We just discussed this scenario and have some ideas.

I know exactly what you're describing, because often we'll have a client who sends several messages in a row. When we reply the oldest one, that buries the intermediate replies by collapsing them, and only showing the latest message (our first reply). We have to intentionally create drafts for the intervening messages to track them or they get ignored. It's not always the same worker handling each message, so the draft hack doesn't always work either.

A big thing we want to avoid is tracking the 'read' status per message per worker. For many reasons. It's a lot of data (1M messages and 100+ workers). Most workers don't need to read every message. By using an individualized 'seen' state to expand/collapse, it means every worker jumping into a ticket with previous activity is having to acknowledge the history to collapse it.

We don't like the distinction being "seen", because I can see something and not be able to act on it right now. It shouldn't then hide the next time I view the ticket.

Additionally, often we reply with "I'll check that out and get right back to you". That inbound message was both seen and replied to, and it still isn't considered to be resolved.

To address all of that, we came up with the concept of "closing" messages within a ticket (regardless of its status).

That has several advantages:

* Outbound messages are always closed/resolved.

* Unresolved messages would always be expanded in the ticket conversation, regardless of their age/sequence. The most recent message is always expanded.

* Unresolved messages could have an icon that makes them obvious.

* A banner at the top of the ticket conversation would display the count of unresolved inbound messages, with a link jumping directly to each one (like drafts). This prevents things from being missed.

* Messages could be marked resolved/unresolved manually. For instance, you could close a 'Thanks' message without having to reply to it.

* Once an inbound message is resolved/closed by one worker, that effort/curation carries over to other workers. Every worker doesn't have to close every message they encounter. Previously encountered issues (like tickets) can be resolved for everyone to focus future effort on yet-unresolved messages.

* After replying to a message, it would be closed by default. This could be overridden on the reply screen in cases like "I'll get right back to you".

* Metrics could be improved by storing a 'resolved at' date on inbound messages.

This would be a pretty minor change, but could significantly improve that workflow.

**Comment by beatbesmer** [comment]
I like this concept. So i asked myself, does it make sense to set the **resolved** status of the inbound message automaticaly by conditional logic or by inserting some specific snippets into the reply. So i came up with the thought about a new #command for outgoing message, which would let you set the status while replying.... 

Or just an option in the reply Form (which also can be set by an shortcut)

**Comment by jstanden** [comment]
Implemented in 9.6
