### ISSUE TITLE
Adding a task directly to a project board column doesn't run its bot behaviors

### ISSUE THREAD

**Issue by Joefatawesome** [jstanden/cerb#717]
When a user manually adds a task by pressing the + button and selecting a task, it will not run the bot behaviors. Issue is not fixed upon reload

**Comment by Joefatawesome** [comment]
![projectboardbotbehavior](https://user-images.githubusercontent.com/24555272/44602203-b1cf8b00-a793-11e8-81ef-26b201b88a4e.png)
For reference

**Comment by jstanden** [comment]
Fixed in 9.0.3
