### ISSUE TITLE
[Workers/Preferences] Bring back 'read all' as a worker mail preference

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#718]

**Comment by jstanden** [comment]
Implemented in 9.0.3

**Comment by jc-dist** [comment]
I'm currently using 9.0.3 and the only spot that I see read all is when I'm viewing a conversation, this needs to be an option that can be selected as a user setting and not just in the conversation view.

**Comment by jstanden** [comment]
@jc-dist It's implemented in the 9.0.3 build from today (2018082701), which will deploy to Cerb Cloud shortly. After that, you'll find it again in worker settings on the 'Mail' tab.
