### ISSUE TITLE
[Improvement Request/ Time Tracking] Add a Calendar button to the log date field

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#729]
Customer requests adding a Calendar button (to pop up a date chooser) to the 'log date' field on the Time Tracking entry form (to make it easier to select a date for the entry)

**Comment by mikron316** [comment]
This was actually working feature in earlier versions (6.x) but was removed 1-2 years ago for weird unknown reason. It's now quite unpleasant to add time tracking for previous dates/weeks "oh sht I forgot to add that vacation day last month" with external calendar and (mis)typing the dates.

Having this feature back would be awesome and shiny!

**Comment by jstanden** [comment]
This was removed unintentionally when a layout cleanup on the time tracking editor popup invalidated the CSS selector that enhanced the date input with the calendar.

**Comment by jstanden** [comment]
Fixed in 9.0.4
