### ISSUE TITLE
Chart: Categories widget does not load when opened in separate tab

### ISSUE THREAD

**Issue by Joefatawesome** [jstanden/cerb#731]
Intent: Open dashboard in another tab to view visualization in widgets.

Result: Chart: Categories widget did not load properly.

Issue is reproducible by using ctrl click on a workspace tab on a Windows machine in chrome browser. Attached file has a screenshot of the issue: 
![chart-categories-error](https://user-images.githubusercontent.com/24555272/44743922-a7293480-aab8-11e8-8ec9-d43c7364c8bc.png)

**Comment by jstanden** [comment]
This was fixed in C3.js v0.6.9:
https://github.com/c3js/c3/releases/tag/v0.6.9

**Comment by jstanden** [comment]
Fixed in 9.2
