### ISSUE TITLE
Error using <enter> when creating new instances of a custom record

### ISSUE THREAD

**Issue by Joefatawesome** [jstanden/cerb#734]
Intent: Create a new instance of a custom record

Result: Page crashed. Result is reproducible by opening up a custom record pop-up and creating a new instance of that custom record. When the user hits enter inside of that pop-up, the page breaks.

**Comment by Joefatawesome** [comment]
This is specific to custom records. I cannot recreate this problem in record types built into cerb

**Comment by jstanden** [comment]
k! Thanks for checking the other record types too. I'll get it patched up.

**Comment by jstanden** [comment]
I can reproduce this.

**Comment by jstanden** [comment]
This also happened on several other record types: project boards, project board columns, profile tabs, profile widgets, etc. Fixing them all.

**Comment by Joefatawesome** [comment]
Oh, I'm sorry I didn't catch that. I checked through about 5 and didn't catch anything and decided they were fine. I will be more thorough next time.

**Comment by jstanden** [comment]
Fixed in 9.0.4
