### ISSUE TITLE
[Enhancement Request] Need a way to differentiate Profile Widgets by target

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#735]
The new profile widgets are great, but in Search -> Profile Widgets, when you search for "org", there are five widgets that are all visually identical in the worklist, though they target different object types.  Is there any way to mark / flag those in such a way that they can be differentiated there?

I know the workaround / preferred method would be to just edit the widget from the actual profile page, but it's a point of confusion.

**Comment by jstanden** [comment]
Agreed! It'd be useful to see the tab record type in the worklist.

**Comment by jstanden** [comment]
As a quick workaround in 9.0.7, the 'Tab' column will be clickable and open a card that shows the record type.

Longer term, we should add a virtual column to widgets so we can display fields from the tab (especially record type).
