### ISSUE TITLE
KB sidebar links aren't working

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#742]
With 9.0.x (through 9.0.3, at present), the links in the support center's knowledgebase sidebar aren't working - they just return raw XML, it looks like.

**Comment by jstanden** [comment]
@Hildy Is this a change in your browser? They're `feed://` URLs, so they attempt to open a feed reader for me. All they do is open RSS (which is an XML format) and the browser decides how to handle that.

**Comment by jstanden** [comment]
Updated the mime type to `application/rss+xml` which should trigger a browser feed reader app.
