### ISSUE TITLE
Button colors in worker UI bots

### ISSUE THREAD

**Issue by Joefatawesome** [jstanden/cerb#745]
Options to color buttons in bot actions do not properly modify button colors:
![image](https://user-images.githubusercontent.com/24555272/44923996-cca77f80-acfe-11e8-9de9-d45b5c7e6a60.png)

**Comment by jstanden** [comment]
This works in customer-facing (portal) bots, but not in worker-facing bots. I'll get it cleaned up.

**Comment by jstanden** [comment]
Fixed in 9.0.4
