### ISSUE TITLE
[Reply] Non-Admin workers unable to preview image in HTML emails

### ISSUE THREAD

**Issue by Joefatawesome** [jstanden/cerb#752]
Intent: To preview an image linked inline in an html email as a non-admin worker. 

Result: User was locked out of viewing its own image. 
![blocked-privilege](https://user-images.githubusercontent.com/24555272/45192533-b701f080-b1fd-11e8-9dd3-e91f62014c4c.png)

**Comment by jstanden** [comment]
I can no longer reproduce this.
