### ISSUE TITLE
[UI/UX] Print stylesheet for profiles

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#755]

**Comment by tomryder-inspirenet** [comment]
We print tickets and individual messages regularly, especially for reference for field engineers who are going places outside of internet/mobile coverage. We'd love to have the old print functionality back, even if made an option, but a useable print media stylesheet that doesn't drop any of the older comments and messages off (as the current one seems to do in every browser but Chrome) would be adequate.

**Comment by jstanden** [comment]
Implemented a basic print stylesheet for profiles in 9.0.5.

We could restore the old print functionality in an optional plugin.
