### ISSUE TITLE
[Translations] Calendar day-of-week headings are not in the translations system

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#756]
The Calendar day of week headings (e.g. Mon, Tue, Wed...) are just in the template*, and not in the translations system.

*cerb/features/cerberusweb.core/templates/internal/calendar/tab.tpl

**Comment by beatbesmer** [comment]
Also on other places, e.g. on a Ticket- Profile:
Widget -> Ticket Fields -> Fields of type _date_ like `created` and `updated` doesn't use the users language

**Comment by jstanden** [comment]
Implemented in 9.0.7
