### ISSUE TITLE
Error when deleting PGP public key

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#757]
When attempting to delete a PGP public key record, and error is returned.  It just says, "An error occurred."  The error is reported regardless of whether or not there are email addresses linked to the key.

**Comment by Hildy** [comment]
The error seems to be related to trying to delete a public key that has a private key linked to it.

**Comment by jstanden** [comment]
We're not going to be able to delete secret keys with gnupg2 the way things are currently set up.

In the meantime, secret keys can be deleted through the normal `gpg2` command-line tools.

1. `cd /path/to/cerb/storage/.gnupg/`
2. `export GNUPGHOME=$(pwd)` 
3. `gpg2 -K` to list secret keys
4. Figure out which key you want to delete and copy its fingerprint.
5. `gpg2 --delete-secret-key <fingerprint>`
6. Confirm multiple times that you're sure.
7. `unset GNUPGHOME`

That's it. You don't need to delete the corresponding public key record in Cerb.

**Comment by jstanden** [comment]
You also need to make sure you're using a GnuPG version >=2.1
