### ISSUE TITLE
[Support Center Portal] Open and Waiting for Reply tickets have status switched

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#764]
The SC Portal displays open tickets as waiting, and waiting tickets as open.  Both in the main list, and when viewing an individual ticket.

**Comment by jstanden** [comment]
@Hildy This is because the perspective changes to the recipient rather than worker, right?

**Comment by jstanden** [comment]
Fixed in 9.0.5

As discussed, these labels are now consistent between workers and the Support Center. The 'waiting' status displays as 'waiting for client' in the Support Center.
