### ISSUE TITLE
[Platform/Mail] Punycode support for email hosts with special characters

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#77]
Waiting on:
https://github.com/swiftmailer/swiftmailer/issues/63

**Comment by jstanden** [comment]
We moved Swiftmailer to Composer in Cerb 8.0+, so it'll be easier to take advantage of this when it's updated in the library.

**Comment by ossinkine** [comment]
I've just published plugin for Swiftmailer which converts domain name to punycode before sending https://github.com/ossinkine/swiftmailer-punycode-plugin. Maybe you will find it useful while we have no official support.

**Comment by jstanden** [comment]
This was implemented in Swiftmailer 6.1.0, and we've upgraded past that now. Closing, since this is no longer an issue and hasn't come up since the first request.
