### ISSUE TITLE
Decimal custom fields count suggestion is not a default

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#774]
When creating a decimal-type custom field, the number of decimal places is suggested at two, but it's not actually a default.  If you leave the suggested "2", it creates the field with zero decimal places.  It's also not a very different color, and not clear that it's just a hint rather than a pre-filled entry.

I would make the decimal places counter more explicit, maybe with a number-entry box like a "number of copies" printer dialog, where it's got an up and down arrow to cycle through the number of decimal points, and perhaps even a 'sample' next to it that goes from '1.23' to '1.23456' as the count increases.

**Comment by jstanden** [comment]
I made this more clear in 9.1.8+
