### ISSUE TITLE
Manager flag for SC logins

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#783]
The general request is for manager access to org tickets in the Support Center, perhaps as a flag on the Contact, so that a manager could log in and see all of the tickets from anyone in that Org.

**Comment by e2env** [comment]
Many of our customers are big companies with IT managers.
They want all there tickets bundled with their account, so this option would be very nice.

**Comment by jstanden** [comment]
We're phasing out the Support Center by 11.0. This would be part of the portal builder.
