### ISSUE TITLE
[Workers] The given organization id is invalid while adding a new worker

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#79]
Adding the org after the fact works fine.

![pasted_image_at_2017_03_01_15_28](https://cloud.githubusercontent.com/assets/652353/23464476/6775b492-fe95-11e6-9f8d-21db8c7a0a11.png)

**Comment by jstanden** [comment]
I couldn't reproduce this, but in looking at the code I see what the issue is.  It's mixing up org/contact ID checks.  I'll push a patch to stable.

**Comment by jstanden** [comment]
Fixed in 7.3.4/stable
