### ISSUE TITLE
New Record Deleted event

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#791]
Requested in relation to deleting a worklist, but should apply in general anywhere.

**Comment by jstanden** [comment]
This will be easier to implement with automations in 10.0+

**Comment by jstanden** [comment]
Now that 10.0 is here we can look at the `record.deleted` event to go along with `record.changed`. It should be really simple to do.

**Comment by jstanden** [comment]
Implemented in 10.4.1 as a `record.changed` input for `change_type == deleted`
