### ISSUE TITLE
URL field doesn't allow accents

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#802]
Tried to save a LinkedIn URL on a contact profile, and the URL had an é in it.  Cerb refused to save it (complaining about needing http:// or https:// in front of the URL, which was already there).  Removing the é allowed the record to be saved.

**Comment by jstanden** [comment]
URLs generally don't allow non-7bit ASCII. Browsers make it seem like they do. Punycode converts UTF-8 in hostnames to 7-bit versions behind the scenes. Special characters are URL-escaped.

We could still make this more user-friendly.
