### ISSUE TITLE
Feature Request: Cancel Sending in Bot Behavior

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#805]
There is not currently any way to prevent a message from being sent in a Behavior.  Customer would like to short-circuit sending based on certain criteria.  We could potentially implement an action to save as a Draft and cancel sending on 'Before message sent from worker'.

**Comment by jstanden** [comment]
This would be far easier in automations where the `return` state would affect this (and subsequent events).

**Comment by jstanden** [comment]
In 10.x, this could be done like the `record.merge` automation event.

Related to #384
