### ISSUE TITLE
Touchscreen issue with pages - drag vs click

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#807]
Reported by a customer, but it also happens on my phone.  His is a Galaxy S9, mine an S6.

When attempting to click on a page on the phone, more often than not it doesn't do anything.  It seems to be trying to grab the drag handle instead of clicking on it.  I have to tap on the logo to return to the main page, instead of clicking my page title in the menu bar.

**Comment by jstanden** [comment]
I believe we fixed this by disabling dragging on mobile Android browsers.
