### ISSUE TITLE
Customfield group linked by bot not on card

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#826]
When a customer fills out a satisfaction survey which gets added to the ticket, via the bot, we see this in the ticket (via the new configurable panels).

However, when you go to edit the ticket, the custom field does not appear and essentially there is no way to delete, edit or correct it.

If you then re-add the same customfield set, it does add this but removes all the data. Likewise, if you then remove it from the ticket, it completely vanishes.

It appears there is some linking missing once added for it to then appear on the ticket card.

**Comment by iammattmartin** [comment]
Note: This has only been an issue since v9.

**Comment by iammattmartin** [comment]
This seems fixed in 9.0.10.

**Comment by jstanden** [comment]
Confirmed. Thanks!
