### ISSUE TITLE
[Mail/Tickets] Clone tickets for parallel handling by different groups

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#837]
Normally this would be handled by linking multiple tasks to a ticket, but tasks currently can't be assigned to an entire group like tickets can. You can currently split a message into a new ticket, but not clone the same message twice.

Cloning a ticket could be accomplished with a bot and packages (or the records API), but we need an example.

Source: https://twitter.com/jscreambe/status/1075138861754396674

**Comment by ScreamBE** [comment]
Hello, here how I did this, would it be a good way of doing this or you think that could cause bad side effects?

        @$message_id = DevblocksPlatform::importGPC($_REQUEST['id'],'integer',0);

        $active_worker = CerberusApplication::getActiveWorker();

        if(false == ($message_to_clone = DAO_Message::get($message_id)))
            return;
		
		if(false == ($ticket = $message_to_clone->getTicket()))
            return;
        
        if(!Context_Message::isWriteableByActor($message_to_clone, $active_worker))
            return;
        
        $message = new CerberusParserMessage();
        
        //remove headers that would put the message to the same old ticket
        foreach($message_to_clone->getHeaders() as $h => $v) {
            switch ($h) {
                case 'message-id':
                case 'in-reply-to':
                case 'references':
                    break;
                case 'subject':
                    $message->headers[$h] = str_replace("#", "", $v);
                    break;
                default:
                    $message->headers[$h] = $v;
            }
        }
    
        $message->body = $message_to_clone->getContent();
        
        if(false === ($new_ticket_id = CerberusParser::parseMessage($message))) {
            return "Couldn't clone the message to a new ticket";
        }
        if(null == ($new_ticket = DAO_Ticket::get($new_ticket_id))) return;
        
        $new_message_id = $new_ticket->first_message_id;
        
        //link attachments
        foreach ($message_to_clone->getAttachments() as $attachment) {
            DAO_Attachment::addLinks(CerberusContexts::CONTEXT_MESSAGE, $new_message_id, $attachment->id);
        }
        if ($message_to_clone->html_attachment_id > 0) {
            DAO_Message::update($new_message_id, array(
                DAO_Message::HTML_ATTACHMENT_ID => $message_to_clone->html_attachment_id,
            ));
        }
        
		//add a comment to the new ticket to inform of the source of the message
        DAO_Comment::create(array(
            DAO_Comment::CREATED => time(),
            DAO_Comment::OWNER_CONTEXT => CerberusContexts::CONTEXT_WORKER,
            DAO_Comment::OWNER_CONTEXT_ID => $active_worker->id,
            DAO_Comment::COMMENT => "Message cloned from ".$ticket->mask.".",
            DAO_Comment::CONTEXT => CerberusContexts::CONTEXT_TICKET,
            DAO_Comment::CONTEXT_ID => $new_ticket_id,
        ));
        
        //link both tickets
        DAO_ContextLink::setLink(CerberusContexts::CONTEXT_TICKET, $ticket->id, CerberusContexts::CONTEXT_TICKET, $new_ticket_id);
        
        //any owner for current ticket? set the same for the new one
        $fields = [
            DAO_Ticket::OWNER_ID => $ticket->owner_id,
        ];
        DAO_Ticket::update($new_ticket_id, $fields);

This being done with a button added on the messages via a plugin and cerberusweb.message.toolbaritem
