### ISSUE TITLE
Broken API on 9.1

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#841]
In: cerb/features/cerberusweb.restapi/api/App.php
      
What are **array_leys** ;)?

`				foreach(array_leys($array['results']) as $k) 
`

Change to array_keys and things work.

**Comment by jstanden** [comment]
Hi Matt!

Not sure how that one got by the syntax checker, but we'll patch it right now.

**Comment by jstanden** [comment]
Fixed in 9.1.1 (the most appropriate maintenance version ever)
