### ISSUE TITLE
[Records/Tickets] Support emoji characters in ticket subjects

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#855]
We need to convert this field to `utf8mb4` and increase the `varchar` length accordingly.

**Comment by iammattmartin** [comment]
Would this cause mails being incorrectly imported? We had one the other day and thought it was just the message itself.

**Comment by jstanden** [comment]
It shouldn't affect anything other than the ticket subject becoming "(no subject)". It's not an issue within the message content because we store those in binary (without a specific encoding).

**Comment by jstanden** [comment]
Implemented in 9.2.
