### ISSUE TITLE
Replace text failing on duplicate text when regexp 

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#870]
We've got a number of replacement rules which all work fine. Today we've been getting email from a customer who seems to repeat the message they've replied to in their reply i.e

---
```
His message


On Wed, 16 Jan 2019 at 18:38, xx xx <mail@domain.com> wrote:
> Hi Customer
> 
> blah content
> more content

On Wed, 16 Jan 2019 at 18:38, xx xx <mail@domain.com> wrote:
> Hi Customer
> 
> blah content
> more content
```

---

Now, the text replacement wasn't matching when running through a bot but checked out via manual regexp testing in the bot itself or via an online tester.

Our matchine rule:

`#On \w{1,10},\D\d{1,2}\D\w{1,10}\D\d{1,4} at \d{1,2}:\d{1,2}, .*wrote:((.|\n)*)#m`

Through testing I changed the replace rule from regexp to just plain text replace from `On Wed, 16 Jan 2019 at 18:38, xx xx <mail@domain.com> wrote:` to `test` and both instances were replaced.

I then edited the original raw message and sent it through with only one of the reply blocks and this matched correctly. Putting both reply blocks back caused a non-match again.

I also removed ALL other matching rules so the replace text function in the `Before new incoming message is accepted` bot was the only action for it to do to avoid inteference from anything else.

Looks like something chokes with it has more than one matching rule when using regexp.

Note: we're using the mail parser cron to pickup the .msg file file the new folder. Using the "import" section in Incoming Email in the GUI has the same issue.

**Comment by jstanden** [comment]
Hi Matt! I'll see if I can reproduce this.

**Comment by jstanden** [comment]
Hi Matt,

I haven't been able to reproduce this. Attached is a bot behavior I was testing with. You can import it somewhere and test it with the simulator. It forces the body content to your test case here:

```
{
    "behavior": {
        "uid": "behavior_1064",
        "title": "Regexp",
        "is_disabled": true,
        "is_private": false,
        "priority": 50,
        "event": {
            "key": "event.mail.before.sent",
            "label": "Before message sent from worker"
        },
        "nodes": [
            {
                "type": "action",
                "title": "Simulator",
                "status": "simulator",
                "params": {
                    "actions": [
                        {
                            "action": "_set_custom_var",
                            "value": "His message\r\n\r\n\r\nOn Wed, 16 Jan 2019 at 18:38, xx xx <mail@domain.com> wrote:\r\n> Hi Customer\r\n> \r\n> blah content\r\n> more content\r\n\r\nOn Wed, 16 Jan 2019 at 18:38, xx xx <mail@domain.com> wrote:\r\n> Hi Customer\r\n> \r\n> blah content\r\n> more content",
                            "format": "",
                            "is_simulator_only": "1",
                            "var": "content"
                        }
                    ]
                }
            },
            {
                "type": "action",
                "title": "Replace",
                "status": "live",
                "params": {
                    "actions": [
                        {
                            "action": "replace_content",
                            "is_regexp": "1",
                            "replace": "#On \\w{1,10},\\D\\d{1,2}\\D\\w{1,10}\\D\\d{1,4} at \\d{1,2}:\\d{1,2}, .*wrote:((.|\\n)*)#m",
                            "replace_mode": "",
                            "with": "Blah"
                        }
                    ]
                }
            }
        ]
    }
}
```

I get this output:

```
>>> Replacing content
Before:
His message


On Wed, 16 Jan 2019 at 18:38, xx xx <mail@domain.com> wrote:
> Hi Customer
> 
> blah content
> more content

On Wed, 16 Jan 2019 at 18:38, xx xx <mail@domain.com> wrote:
> Hi Customer
> 
> blah content
> more content

After:
His message


Blah
```

**Comment by iammattmartin** [comment]
The behaviour is not consistent because it is only happening with parsed mail. In the bot it matched.

We have another example. It is validating against every regexp tester we can find (two being https://regex101.com/ and https://www.debuggex.com/#cheatsheet) but cerb just ignores them. i.e

```
#^[a-zA-Z].*@.* wrote:\n{1,}>( |  |\n|.*){2,}#m
```

Testing elsewhere as `^[a-zA-Z].*@.* wrote:\n{1,}>( |  |\n|.*){2,}/m` changes the following:

From:
```
https://www.senderurl.com

Please contact our sales team (something@domain.com) for details.
************************************************************************

Some Email <email@domain.com> wrote:

> Hi Support,
>
> This does not really work etc etc etc .
>
> This may be something we fix in the future.
```

To:

```
https://www.senderurl.com

Please contact our sales team (something@domain.com) for details.
************************************************************************
```

I've disabled everything else in the bot to leave just the one and it just does nothing when parsing actual real email but via the bot again, it matches and strips.

**Comment by jstanden** [comment]
k! I'll see if I can reproduce with parsed mail (using `run()` rather than `simulate()`).

I'm testing now and I'll ping back in a few.

**Comment by iammattmartin** [comment]
Is there any other testing I can do from this side to narrow it down on the parse? It just looks like it is choking on something and skipping things. 

Will try and help where possible.

**Comment by jstanden** [comment]
Perhaps I'm just using the wrong event.

I used this filtering behavior:

```
{
    "behavior": {
        "uid": "behavior_filter_quoted",
        "title": "Strip quoted blocks in inbound mail",
        "is_disabled": false,
        "is_private": false,
        "priority": 50,
        "event": {
            "key": "event.mail.received.app",
            "label": "Before new incoming message is accepted"
        },
        "nodes": [
            {
                "type": "action",
                "title": "Replace body",
                "status": "live",
                "params": {
                    "actions": [
                        {
                            "action": "replace_content",
                            "is_regexp": "1",
                            "replace": "#^[a-zA-Z].*@.* wrote:\\n{1,}>( |  |\\n|.*){2,}#m",
                            "replace_mode": "",
                            "with": ""
                        }
                    ]
                }
            }
        ]
    }
}
```

With this message source in `./storage/mail/new/`:

```
From: customer@cerb.example
To: support@cerb.example
Subject: Help with regexp

https://www.senderurl.com

Please contact our sales team (something@domain.com) for details.
************************************************************************

Some Email <email@domain.com> wrote:

> Hi Support,
>
> This does not really work etc etc etc .
>
> This may be something we fix in the future.
```

And the saved ticket message body was:

<img width="441" alt="cerb_filter_regexp" src="https://user-images.githubusercontent.com/63288/53111643-538d2600-34f2-11e9-9198-443f9133c23e.png">

Can you share the exact behavior and raw message source you're using to test?

**Comment by jstanden** [comment]
PHP 7.2.10
PCRE Library Version => 8.41 2017-07-05

I can spin up a few different versions and see if I get different results.

**Comment by iammattmartin** [comment]
7.2.15 / 8.39 2016-06-14 here.

I imported that bot and disabled all my other "Before new incoming message is accepted" bots. Didn't work. :(

**Comment by iammattmartin** [comment]
In the same bot I replaced a normal word (straight text replace, non regexp), and it stripped that but not the regexp.

I've broken down the rule.
`.* <.*@.*> wrote.*` worked, matching the testers
`^.* <.*@.*> wrote.*` worked, matching the testers
`^[a-zA-Z].*@.* wrote.*` worked, matching the testers
`^[a-zA-Z].*@.* wrote:\n{1,}>` failed, didn't match testers (will remove some on next)
`^[a-zA-Z].*@.* wrote:\n` failed, didn't match testers

If I then use the latter part of the rule after the \n (and by adding a > although works without)..

`^>( |  |\n|.*|){2,}` worked, matching testers.
It has an \n but I wonder if that is skipped due to the first match of ` ` and `  ` (single and double space) so I reduced to `^>(\n|.*|){2,}` which also worked fine.

Then reduced to `^> \n{0,}` with worked for what we needed to test.

I can't really work out why, at the moment, the first \n causes this to break whereas the second used in a similar way is fine.

**Comment by iammattmartin** [comment]
Further to this, it does look like odd processing of \n and maybe \r\n.

Putting \n in () did nothing but \r\n did and worked.

So my original rule is now fine but with (\r\n). 

It's still a bit strange that what works in the tools does not in cerb in the same way.

I will re-test on the original matching issue though as I suspect that may even be similarly related now.

**Comment by jstanden** [comment]
It's very likely that the line endings in browser-based regexp testing tools are being normalized by your browser to your OS's preference (LF=Mac/Unix, CRLF=Windows).

With inbound email, MUAs and MTAs are supposed to normalize line endings to CRLF per the [RFC-2822 spec](https://www.ietf.org/rfc/rfc2822.txt).

In my test, I wrote the inbound message in a text editor on a Mac, so my line endings were LF and matched the regexp. I should have done a `unix2dos` on that first.

**Comment by iammattmartin** [comment]
Could certainly be that..

Although the text I posted in to the import mail text box and that pasted in to the bot were the same (one copy, two pastes) so you'd expect them to have the same line endings.

We'll likely get some more messages through so will monitor but will still need to play with the first message example as not sure line endings would be causing that although could be wrong.

**Comment by jstanden** [comment]
We refactored the 'Replace text in message content' action in 9.6. If this is still an issue, you'll have to give it another test when that's pushed.
