### ISSUE TITLE
[Feature Request] Add ability to hide / remove default fields

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#871]
This is something that came up in talking about adding custom fields to contacts and how the customer could add whatever they wanted...

Their organization is prohibited from storing Date of Birth (due to their interpretation of GDPR), and they'd like to not have that field on the Contact object at all.

**Comment by jstanden** [comment]
The field could be hidden with the card editor behaviors in 9.2+. As well, a record changed behavior could wipe out any field values if set another way (API, bots, etc).

We could spin off DOB from contacts to a custom field since nothing internally relies on it.

**Comment by jstanden** [comment]
This should be configurable with KATA somewhere.
