### ISSUE TITLE
In Chinese, if the font is GB2312 coded, the message content not be viewed

### ISSUE THREAD

**Issue by xtaler** [jstanden/cerb#899]
Hi,

If in Chinese, the font is GB2312 codedm the conent text/html won't be viewed, only one line ,/div> showed,

The message can be viewed in roundcube and outlook. But failed in cerb. If you quote and reply, the content will be showed as quoted.

some thing from message head information

------=_002_NextPart488055172523_=----
Content-Type: text/html;
	charset="GB2312"
Content-Transfer-Encoding: quoted-printable

<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charse=
t=3DGB2312"><style>body { line-height: 1.5; }blockquote { margin-top: 0px;=
 margin-bottom: 0px; margin-left: 0.5em; }p { margin-top: 0px; margin-bott=
om: 0px; }div.foxdiv20190213163131686177 { }body { font-size: 10.5pt; font=
-family: Verdana; color: rgb(0, 0, 0); line-height: 1.5; }</style>

Thanks .

Desmond

**Comment by jstanden** [comment]
Thanks for the report, Desmond! I'll give it a test.

Do you have the `iconv` extension installed in PHP? Cerb will use it in addition to mbstring when available, and it's capable of converting more encodings to UTF-8.

**Comment by xtaler** [comment]
Thanks for your respond.

Yes, extension iconv installed ,
Best regards.

**Comment by jstanden** [comment]
Does this patch work?
[cerb92_gb2312.diff.txt](https://github.com/jstanden/cerb/files/2882569/cerb92_gb2312.diff.txt)

If you have a copy of the original message source you could retry it in Setup->Mail->Incoming->Import, or copy it to `./storage/mail/new/` with a `.msg` extension.

**Comment by xtaler** [comment]
Hi
Sorry for late reply. I tested to apply the patch, but failed. the output is:
git apply cerb92_gb2312.diff                                 
cerb92_gb2312.diff:39: trailing whitespace.

cerb92_gb2312.diff:60: trailing whitespace.

cerb92_gb2312.diff:90: trailing whitespace.

error: patch failed: api/app/Parser.php:707
error: api/app/Parser.php: patch does not apply
+++++
By the way, I download the diff file in windows system, then upload to server, I don't know if this is not good for diff file to apply. I can not visit amazonaws.com from here. I have to using proxy, wget does not work at the server without proxy.
Thanks

**Comment by jstanden** [comment]
Hi Desmond. The whitespace warnings in the patch can be ignored. Which Cerb version are you currently using?

**Comment by xtaler** [comment]
Hi
The Cerb version is 9.1.7, I try to update to 9.2.0, but  git say 9.1.7 is the latest. 

thanks
