### ISSUE TITLE
Hitting "Save and Continue" and "Save and Close" in rapid succession on a new Role allows the creation of duplicate Roles

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#904]
kindof a double-click issue.

**Comment by jstanden** [comment]
The single button version isn't possible in 9.2 onwards. There's a spinner on the 'Save changes' button in all popup editors, and the button disables.

It would probably still be an issue if you clicked both buttons. I'll take a look.

**Comment by jstanden** [comment]
Fixed in 9.1.6
