### ISSUE TITLE
Dynamic picklists

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#922]
Request is for picklists / CFs that depend on earlier selections (like a car finder, which goes Make -> Model -> Trim).  Use case is for tagging / statistics.  More details in thread at APD-51375-924.

**Comment by kiranos** [comment]
@jstanden will this perhaps make it into 9.4 ?

**Comment by jstanden** [comment]
This is exactly what interactions do in 10.0. There could be a custom field type that has its value set from an interaction.
