### ISSUE TITLE
Error after upgrade: Undefined class constant 'EXTENSION_ID'

### ISSUE THREAD

**Issue by DigNative** [jstanden/cerb#931]
I was trying to upgrade our existing Cerb 7.1.1 installation to v9.2.2 by following the [upgrade instructions](https://cerb.ai/docs/upgrading/). Upon first access to the upgraded web interface, I am prompted to complete the upgrade, which then results in following error:

```
<b>Fatal error</b>:  Uncaught Error: Undefined class constant 'EXTENSION_ID' in [CERB_PATH]/mail/storage/plugins/wgm.ldap/patches/8.0.0.php:26
Stack trace:
#0 [CERB_PATH]/mail/libs/devblocks/api/Model.php(2736): require_once()
#1 [CERB_PATH]/mail/api/Application.class.php(542): DevblocksPatch-&gt;run()
#2 [CERB_PATH]/mail/api/app/Update.php(162): CerberusApplication::update()
#3 [CERB_PATH]/mail/api/Application.class.php(288): ChUpdateController-&gt;handleRequest(Object(DevblocksHttpRequest))
#4 [CERB_PATH]/mail/index.php(114): CerberusApplication::processRequest(Object(DevblocksHttpRequest))
#5 {main}
  thrown in <b>[CERB_PATH]/mail/storage/plugins/wgm.ldap/patches/8.0.0.php</b> on line <b>26</b><br />
```

**Comment by jstanden** [comment]
Hey there,

You can delete the `./storage/plugins/wgm.ldap/` plugin directory before the update.

Then upgrade from 7.1.1 to 9.2.2, and reinstall the LDAP plugin from Setup->Plugins->Library.

Cerb should do that for you, but it may not have permissions to update/remove the old plugin.
