### ISSUE TITLE
Allow adding / removing of Roles from the Worker Property

### ISSUE THREAD

**Issue by rmiddle** [jstanden/cerb#94]
Every time someone other them me adds a worker they forgot to add them to a role.  With the changes in 7.3 and moving the workers and roles outside of the setup section that makes it even worse.

**Comment by jstanden** [comment]
I agree with the usability of this. We'd just need to check that the roles are worker-based (rather than group/everyone).

**Comment by jstanden** [comment]
In 8.3 I'd like to make roles assigned directly to workers and bots. Then we'd be able to do things like this a lot more easily; while at the same time conceptually cleaning things up.

**Comment by jstanden** [comment]
This is no longer necessary in 9.2 with the dynamic role rosters.
