### ISSUE TITLE
"New task for me" library entry doesn't bundle owner right away

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#946]
When creating a new task from the 'Build' tab, the assigned worker is part of the new task from the beginning (i.e. a behavior that watches the new task event can tell the task is assigned, and who it's assigned to).  When creating a new task from the library's "new task for me" entry, that same behavior can't tell who the task owner is.

**Comment by jstanden** [comment]
@Hildy Have a sample behavior?

**Comment by jstanden** [comment]
Fixed in 9.3.1
