### ISSUE TITLE
Bot import/export doesn't include the bot's @mention

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#973]
Bot import/export doesn't currently show the bot's @mention (or allow it to be imported).  It's required to be set post-import.

**Comment by jstanden** [comment]
This is primarily because the bot mention must be unique, so it would prevent export/import in the same system. The bot mentions are used anywhere, so we can certainly make that a non-required field.

**Comment by jstanden** [comment]
The mention field doesn't appear to be required in 9.4+ (perhaps earlier).
