### ISSUE TITLE
Downloads don't work when clicking the text itself

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#998]
Chrome 77.0.3865.90, Windows 10 Pro

Downloading attachments from a message on a ticket, when I click the `v` then `Download`, nothing happens.  If I click the `v` and then anywhere on the highlighted download line that *isn't* the `Download` text itself, it works.

**Comment by Hildy** [comment]
Still happening in 9.4 beta.

**Comment by jstanden** [comment]
Fixed in 10.0.5
