### ISSUE TITLE
Encoded filenames don't match behavior criteria

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#999]
Client is trying to match an attachment filename as a behavior criteria, but the filename is UTF-8 encoded in the email, and the criteria is apparently doing a straight text match against the encoded string (which, obviously, fails).

We need to decode the filename before trying to match it.

**Comment by jstanden** [comment]
This isn't actually a bug. The filename decoding works fine. The client's issue is they were changing the plaintext part but viewing the HTML part.
